const Setting = require("../models/Setting");
const TEMPLATE_KEYS=["bookingReceived","bookingConfirmed","paymentRejected","bookingCancelled","bookingExpired","cancellationRequested","refundRequest","extraRequest","reschedulePayment","paymentProof","checkedIn","checkedOut","bookingActivity","paymentProofReceived","adminNewBooking","adminBookingActivity","other"];
const DEFAULT_TEMPLATES=Object.freeze(Object.fromEntries(TEMPLATE_KEYS.map(key=>[key,{enabled:false,subject:"{{originalSubject}}",body:"{{originalContent}}"}])));
const DEFAULT_EMAIL_NOTIFICATION_DESIGN=Object.freeze({version:1,themeEnabled:false,brandName:"CA Smart Staycation",headerText:"CA Smart Staycation",footerText:"Thank you for choosing CA Smart Staycation.",pageBackgroundColor:"#f3f0e7",cardBackgroundColor:"#ffffff",headerBackgroundColor:"#063b32",accentColor:"#c9a44c",textColor:"#26352f",mutedTextColor:"#6b746f",buttonBackgroundColor:"#c9a44c",buttonTextColor:"#063b32",cardRadius:16,templates:DEFAULT_TEMPLATES});
let cached=null,cacheUntil=0;
function mergedEmailNotificationDesign(value){const source=value&&typeof value==="object"&&!Array.isArray(value)?value:{},sourceTemplates=source.templates&&typeof source.templates==="object"?source.templates:{},templates={};TEMPLATE_KEYS.forEach(key=>{const src=sourceTemplates[key]&&typeof sourceTemplates[key]==="object"?sourceTemplates[key]:{};templates[key]={...DEFAULT_TEMPLATES[key],...src};});return{...DEFAULT_EMAIL_NOTIFICATION_DESIGN,...source,templates,version:1};}
function validColor(value){return/^#[0-9a-f]{6}$/i.test(String(value||""));}
function sanitizeEmailNotificationDesign(input){const source=input&&typeof input==="object"&&!Array.isArray(input)?input:{},clean={},colors=["pageBackgroundColor","cardBackgroundColor","headerBackgroundColor","accentColor","textColor","mutedTextColor","buttonBackgroundColor","buttonTextColor"];colors.forEach(key=>{if(!(key in source))return;if(!validColor(source[key]))throw new Error(`Invalid color for ${key}.`);clean[key]=String(source[key]).toLowerCase();});if("themeEnabled" in source)clean.themeEnabled=Boolean(source.themeEnabled);["brandName","headerText","footerText"].forEach(key=>{if(key in source)clean[key]=String(source[key]??"").slice(0,500);});if("cardRadius" in source){const n=Number(source.cardRadius);if(!Number.isFinite(n)||n<0||n>50)throw new Error("Invalid value for cardRadius.");clean.cardRadius=n;}if(source.templates&&typeof source.templates==="object"){clean.templates={};TEMPLATE_KEYS.forEach(key=>{const src=source.templates[key];if(!src||typeof src!=="object")return;clean.templates[key]={enabled:Boolean(src.enabled),subject:String(src.subject??"{{originalSubject}}").slice(0,300),body:String(src.body??"{{originalContent}}").slice(0,12000)};});}return clean;}
function invalidateEmailDesignCache(){cached=null;cacheUntil=0;}
async function getEmailNotificationDesign(){if(cached&&Date.now()<cacheUntil)return cached;const settings=await Setting.findOne().select("guestBookingPage").lean(),booking=settings?.guestBookingPage&&typeof settings.guestBookingPage==="object"?settings.guestBookingPage:{};cached=mergedEmailNotificationDesign(booking.emailNotificationDesign);cacheUntil=Date.now()+60000;return cached;}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));}
function stripTags(value){return String(value||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();}
function classifySubject(subject){const s=String(subject||"");if(/^Booking Received\b/i.test(s))return"bookingReceived";if(/^Booking Confirmed\b/i.test(s))return"bookingConfirmed";if(/^Payment Proof Rejected\b/i.test(s))return"paymentRejected";if(/^Booking Cancelled\b/i.test(s))return"bookingCancelled";if(/^Booking Expired\b/i.test(s))return"bookingExpired";if(/^Cancellation Request\b/i.test(s))return"cancellationRequested";if(/^Refund Request/i.test(s))return"refundRequest";if(/^(Extra Guest|Extra Set of Amenities) Request/i.test(s))return"extraRequest";if(/^Reschedule Payment/i.test(s))return"reschedulePayment";if(/^Payment Proof Received/i.test(s))return"paymentProofReceived";if(/^Payment Proof/i.test(s))return"paymentProof";if(/^Guest Checked In/i.test(s))return"checkedIn";if(/^Guest Checked Out/i.test(s))return"checkedOut";if(/^Booking Activity Updated/i.test(s))return"bookingActivity";if(/^New Booking\b/i.test(s))return"adminNewBooking";if(/^Booking Activity\b/i.test(s))return"adminBookingActivity";return"other";}
function extractContext(subject,html){const source=String(html||""),refMatch=String(subject||"").match(/[—-]\s*([A-Za-z0-9][A-Za-z0-9-]{3,})\s*$/),dear=source.match(/<p[^>]*>\s*Dear\s+([^,<]+),?/i),adminGuest=source.match(/<strong>Guest:\s*<\/strong>\s*([^<]+)/i),login=source.match(/href=["']([^"']*guest-login[^"']*)["']/i);return{originalSubject:String(subject||""),originalContent:source,bookingReference:refMatch?.[1]||"",guestName:stripTags(dear?.[1]||adminGuest?.[1]||"Guest"),loginUrl:login?.[1]||"https://www.casmartstaycation.com/guest-booking/guest-login.html",today:new Date().toLocaleDateString("en-PH")};}
function renderSubject(template,context){return String(template||"{{originalSubject}}").replace(/{{\s*([a-zA-Z0-9_]+)\s*}}/g,(_,key)=>key==="originalContent"?"":stripTags(context[key]??"")).replace(/[\r\n]+/g," ").slice(0,300);}
function renderBody(template,context,design){const originalMarker="__CA_ORIGINAL_CONTENT__",buttonMarker="__CA_LOGIN_BUTTON__";let text=String(template||"{{originalContent}}").replace(/{{\s*originalContent\s*}}/gi,originalMarker).replace(/{{\s*loginButton\s*}}/gi,buttonMarker);text=text.replace(/{{\s*([a-zA-Z0-9_]+)\s*}}/g,(_,key)=>String(context[key]??""));text=escapeHtml(text).replace(/\r?\n/g,"<br>");text=text.replace(new RegExp(originalMarker,"g"),context.originalContent);const loginButton=`<a href="${escapeHtml(context.loginUrl)}" style="display:inline-block;margin:14px 0;padding:12px 18px;border-radius:8px;background:${design.buttonBackgroundColor};color:${design.buttonTextColor};text-decoration:none;font-weight:700;">Open Guest Account</a>`;return text.replace(new RegExp(buttonMarker,"g"),loginButton);}
function wrapTheme(inner,design){if(!design.themeEnabled)return inner;const radius=Number(design.cardRadius)||0,styled=String(inner||"").replace(/<a\s+(?![^>]*style=)/gi,`<a style="color:${design.accentColor};font-weight:700;" `);return`<!doctype html><html><body style="margin:0;padding:0;background:${design.pageBackgroundColor};font-family:Arial,Helvetica,sans-serif;color:${design.textColor};"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:${design.pageBackgroundColor};padding:28px 12px;"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:${design.cardBackgroundColor};border-radius:${radius}px;overflow:hidden;border:1px solid ${design.accentColor}33;"><tr><td style="padding:20px 28px;background:${design.headerBackgroundColor};color:#fff;"><div style="font-size:12px;letter-spacing:2px;color:${design.accentColor};font-weight:700;">${escapeHtml(design.brandName)}</div><div style="font-size:26px;font-family:Georgia,'Times New Roman',serif;margin-top:5px;">${escapeHtml(design.headerText)}</div></td></tr><tr><td style="padding:26px 28px;font-size:15px;line-height:1.65;color:${design.textColor};">${styled}</td></tr><tr><td style="padding:16px 28px;background:${design.pageBackgroundColor};color:${design.mutedTextColor};font-size:12px;text-align:center;">${escapeHtml(design.footerText)}</td></tr></table></td></tr></table></body></html>`;}
async function prepareDesignedEmail(subject,html){try{const design=await getEmailNotificationDesign(),context=extractContext(subject,html),key=classifySubject(subject),template=design.templates?.[key]||DEFAULT_TEMPLATES.other,finalSubject=template?.enabled?renderSubject(template.subject,context):String(subject||""),inner=template?.enabled?renderBody(template.body,context,design):String(html||"");return{subject:finalSubject||String(subject||""),html:wrapTheme(inner,design),templateKey:key};}catch(err){console.error("EMAIL DESIGN PREPARE ERROR:",err&&err.message?err.message:err);return{subject:String(subject||""),html:String(html||""),templateKey:"other"};}}
module.exports={TEMPLATE_KEYS,DEFAULT_EMAIL_NOTIFICATION_DESIGN,mergedEmailNotificationDesign,sanitizeEmailNotificationDesign,invalidateEmailDesignCache,getEmailNotificationDesign,classifySubject,prepareDesignedEmail};
