/* Guest add-on requests: additional adults and linen/toiletry sets, ₱300 each, payment proof required. */
(function(){
  const API="https://ca-smart-staycation-muqd.onrender.com/api", tokenKey="guestAuthToken";
  const auth=()=>({Authorization:`Bearer ${localStorage.getItem(tokenKey)||""}`});
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let bookings=[];
  function injectStyle(){if(document.getElementById('guestAddOnStyles'))return;const s=document.createElement('style');s.id='guestAddOnStyles';s.textContent='.addon-btn{background:#0b5d4d!important}.addon-panel{border:1px solid #d9e3df;border-radius:9px;padding:14px;margin-top:12px;background:#fafcfb}.addon-panel h4{margin:0 0 7px;color:#0b5d4d}.addon-panel p{margin:5px 0;color:#68736e;font-size:13px;line-height:1.5}.addon-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.addon-grid label{font-size:13px;font-weight:700;color:#33423d}.addon-grid input{width:100%;box-sizing:border-box;margin-top:5px;height:40px;padding:8px;border:1px solid #d5ddd9;border-radius:6px}.addon-total{margin-top:10px;font-weight:700}.addon-proof{margin-top:10px}.addon-modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.55);display:flex;align-items:center;justify-content:center;z-index:9999;padding:15px}.addon-modal{width:min(520px,100%);background:#fff;border-radius:12px;padding:20px;box-sizing:border-box;max-height:90vh;overflow:auto}.addon-modal h3{margin-top:0;color:#0b5d4d}.addon-modal-actions{display:flex;gap:8px;margin-top:14px}.addon-modal-actions button{flex:1}.addon-cancel{background:#777!important}@media(max-width:600px){.addon-grid{grid-template-columns:1fr}.addon-modal-actions{flex-direction:column}}';document.head.appendChild(s)}
  async function loadBookings(){try{const r=await fetch(`${API}/guest-auth/me`,{headers:auth(),cache:'no-store'});const d=await r.json();if(r.ok&&d.success)bookings=d.bookings||[];renderButtons()}catch(e){console.warn('ADD-ON LOAD:',e.message)}}
  function renderButtons(){document.querySelectorAll('.booking-card').forEach(card=>{if(card.querySelector('.guest-addon-request-btn'))return;const ref=card.querySelector('.reference')?.textContent?.trim();const b=bookings.find(x=>x.bookingReference===ref);if(!b||!['Reserved','Confirmed','Checked In'].includes(b.bookingStatus))return;const actions=card.querySelector('.booking-actions');if(!actions)return;const btn=document.createElement('button');btn.className='secondary addon-btn guest-addon-request-btn';btn.textContent='Request Additional Guest / Amenities';btn.onclick=()=>openModal(b);actions.appendChild(btn);const pending=(b.addOnRequests||[]).filter(x=>x.status==='Pending Verification');if(pending.length){const box=document.createElement('div');box.className='addon-panel';box.innerHTML=`<h4>Additional Requests</h4>${pending.map(x=>`<p><strong>Pending verification:</strong> ${Number(x.extraGuests||0)} additional guest(s) + ${Number(x.amenitySets||0)} linen/toiletry set(s) · ₱${Number(x.amount||0).toLocaleString()}</p>`).join('')}`;card.querySelector('.details')?.appendChild(box)}})}
  function openModal(b){injectStyle();const max=Math.max(0,4-Number(b.adults||0));const back=document.createElement('div');back.className='addon-modal-backdrop';back.innerHTML=`<div class="addon-modal"><h3>Request Additional Guest / Amenities</h3><p><strong>${esc(b.bookingReference)}</strong></p><p>Each additional adult guest is <strong>₱300</strong>. One complete additional set of <strong>towel + toiletries + bedsheet + blanket</strong> is also considered one additional guest and costs <strong>₱300</strong>.</p><p>You must upload payment proof immediately. The request is subject to admin payment verification.</p><div class="addon-grid"><label>Additional adult guests (max ${max})<input id="addonGuests" type="number" min="0" max="${max}" value="0"></label><label>Additional complete linen/toiletry sets<input id="addonSets" type="number" min="0" max="10" value="0"></label></div><div class="addon-total">Amount to pay: <span id="addonAmount">₱0</span></div><div class="addon-proof"><label><strong>Upload payment proof *</strong><input id="addonProof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></label></div><div class="addon-modal-actions"><button class="addon-cancel" id="addonCancel">Cancel</button><button id="addonSubmit">Submit Request & Payment Proof</button></div></div>`;document.body.appendChild(back);const g=back.querySelector('#addonGuests'),s=back.querySelector('#addonSets'),amt=back.querySelector('#addonAmount'),update=()=>{amt.textContent=`₱${((Number(g.value)||0)+(Number(s.value)||0))*300}`};g.addEventListener('input',update);s.addEventListener('input',update);back.querySelector('#addonCancel').onclick=()=>back.remove();back.addEventListener('click',e=>{if(e.target===back)back.remove()});back.querySelector('#addonSubmit').onclick=async()=>{const extraGuests=Math.max(0,Math.min(max,Number(g.value)||0)),amenitySets=Math.max(0,Number(s.value)||0),file=back.querySelector('#addonProof').files[0],amount=(extraGuests+amenitySets)*300;if(!amount)return alert('Select at least one additional guest or amenity set.');if(!file)return alert('Payment proof is required before submitting the request.');const fd=new FormData();fd.append('extraGuests',extraGuests);fd.append('amenitySets',amenitySets);fd.append('paymentProof',file);const btn=back.querySelector('#addonSubmit');btn.disabled=true;btn.textContent='Submitting...';try{const r=await fetch(`${API}/guest-auth/bookings/${encodeURIComponent(b._id)}/add-ons`,{method:'POST',headers:auth(),body:fd});const d=await r.json();if(!r.ok)throw Error(d.message||'Unable to submit request.');alert(d.message);back.remove();await loadBookings()}catch(e){alert(e.message);btn.disabled=false;btn.textContent='Submit Request & Payment Proof'}}}
  function start(){injectStyle();loadBookings();const obs=new MutationObserver(()=>renderButtons());obs.observe(document.body,{childList:true,subtree:true});setTimeout(()=>obs.disconnect(),15000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
