const express = require("express");
const jwt = require("jsonwebtoken");
const crypto = require("crypto");
const Booking = require("../models/Booking");
const Notification = require("../models/Notification");
const Setting = require("../models/Setting");
const sendEmail = require("../mail/sendEmail");
const router = express.Router();
const DEFAULT_ADMIN_EMAIL = "markryantamayo@gmail.com";
const LOGIN_URL = process.env.GUEST_LOGIN_URL || "https://casmartstaycation.github.io/cassbooking/guest-booking/guest-login.html";
function adminConfig(){const password=String(process.env.ADMIN_PASSWORD||"");const email=String(process.env.ADMIN_EMAIL||DEFAULT_ADMIN_EMAIL).trim().toLowerCase();const secret=String(process.env.ADMIN_JWT_SECRET||process.env.JWT_SECRET||(password?crypto.createHash("sha256").update(`ca-smart-admin:${password}`).digest("hex"):""));return{email,secret};}
function requireAdmin(req,res,next){const{email,secret}=adminConfig();const header=req.headers.authorization||"";const token=header.startsWith("Bearer ")?header.slice(7):"";if(!token||!secret)return res.status(401).json({success:false,message:"Admin authentication required."});try{const payload=jwt.verify(token,secret);if(payload.role!=="admin"||String(payload.email||"").toLowerCase()!==email)return res.status(403).json({success:false,message:"Admin access required."});req.admin=payload;next();}catch(_){return res.status(401).json({success:false,message:"Admin session expired or invalid."});}}
function dateText(v){const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("en-PH",{year:"numeric",month:"long",day:"numeric"});}
function money(v){return `₱${Number(v||0).toLocaleString("en-PH")}`;}
async function getAdminContact(){try{const s=await Setting.findOne().select("adminContactNumber").lean();return String(s?.adminContactNumber||process.env.ADMIN_CONTACT_NUMBER||"").trim();}catch(_){return String(process.env.ADMIN_CONTACT_NUMBER||"").trim();}}
async function getAdminEmail(){try{const s=await Setting.findOne().select("adminNotificationEmail").lean();return String(s?.adminNotificationEmail||process.env.ADMIN_EMAIL||DEFAULT_ADMIN_EMAIL).trim().toLowerCase();}catch(_){return String(process.env.ADMIN_EMAIL||DEFAULT_ADMIN_EMAIL).trim().toLowerCase();}}
function updateMessage(booking,changedFields){if(changedFields.includes("bookingStatus")&&booking.bookingStatus==="Cancelled")return{title:"Booking Cancelled",message:`Booking ${booking.bookingReference} has been cancelled by CA Smart Staycation.`,type:"booking-cancelled"};if(changedFields.includes("bookingStatus")&&booking.bookingStatus==="Expired")return{title:"Booking Expired",message:`Booking ${booking.bookingReference} has expired because payment was not completed within the required period.`,type:"booking-expired"};if(changedFields.includes("paymentStatus"))return{title:"Payment Status Updated",message:`Payment status for booking ${booking.bookingReference} is now ${booking.paymentStatus}.`,type:"payment-status-updated"};if(changedFields.includes("refundStatus"))return{title:"Refund Status Updated",message:`Refund status for booking ${booking.bookingReference} is now ${booking.refundStatus}.`,type:"refund-status-updated"};return{title:"Booking Updated",message:`Booking ${booking.bookingReference} has been updated by CA Smart Staycation.`,type:"booking-updated"};}
async function notifyBoth(booking,changedFields){const info=updateMessage(booking,changedFields);const adminEmail=await getAdminEmail();const adminContact=await getAdminContact();const guestEmail=String(booking.email||"").trim().toLowerCase();const guestName=`${booking.firstName||""} ${booking.lastName||""}`.trim()||"Guest";const reason=booking.bookingStatus==="Cancelled"&&booking.cancellationReason?`<p><strong>Cancellation reason:</strong> ${String(booking.cancellationReason)}</p>`:"";const details=`<p><strong>Booking Reference:</strong> ${booking.bookingReference}<br><strong>Check-in:</strong> ${dateText(booking.checkIn)}<br><strong>Check-out:</strong> ${dateText(booking.checkOut)}<br><strong>Total Amount:</strong> ${money(booking.totalAmount)}<br><strong>Booking Status:</strong> ${booking.bookingStatus}<br><strong>Payment Status:</strong> ${booking.paymentStatus}</p>`;const contactBlock=adminContact?`<div style="margin-top:20px;padding:14px 16px;border:1px solid #d7e1dc;border-left:4px solid #173f35;border-radius:7px;background:#f7faf8"><strong>Need help or have a request?</strong><br>Please contact CA Smart Staycation Admin at <strong>${adminContact}</strong>.</div>`:`<p style="margin-top:20px"><strong>Need help or have a request?</strong><br>Please contact CA Smart Staycation Admin for assistance.</p>`;const guestHtml=`<h2>CA Smart Staycation</h2><p>Dear ${guestName},</p><p>${info.message}</p>${reason}${details}<p><a href="${LOGIN_URL}">Open your guest account</a></p>${contactBlock}`;const adminHtml=`<h2>CA Smart Staycation Admin Notification</h2><p>A booking has been updated.</p>${details}<p><strong>Guest:</strong> ${guestName}<br><strong>Guest Email:</strong> ${guestEmail||"—"}<br><strong>Changed fields:</strong> ${changedFields.join(", ")}</p>${reason}<p>${info.message}</p>`;await Promise.allSettled([guestEmail?sendEmail(guestEmail,`${info.title} — ${booking.bookingReference}`,guestHtml):Promise.resolve(),adminEmail?sendEmail(adminEmail,`Booking Update — ${booking.bookingReference}`,adminHtml):Promise.resolve()]);await Promise.allSettled([guestEmail?Notification.create({recipientType:"guest",recipientEmail:guestEmail,booking:booking._id,title:info.title,message:info.message,type:info.type,read:false}):Promise.resolve(),adminEmail?Notification.create({recipientType:"admin",recipientEmail:adminEmail,booking:booking._id,title:`Booking Update — ${booking.bookingReference}`,message:info.message,type:info.type,read:false}):Promise.resolve()]);}
router.put("/bookings/:id",requireAdmin,async(req,res)=>{try{const booking=await Booking.findById(req.params.id);if(!booking)return res.status(404).json({success:false,message:"Booking not found."});const allowed=["bookingStatus","paymentStatus","refundStatus","refundAmount","refundFee","refundPolicyRule","refundProcessedAt","refundProcessedBy","cancellationReason","cancellationRequestedAt","notes","housekeepingStatus"];const changedFields=[];for(const key of allowed){if(Object.prototype.hasOwnProperty.call(req.body||{},key)&&String(booking[key]??"")!==String(req.body[key]??"")){booking[key]=req.body[key];changedFields.push(key);}}if(!changedFields.length)return res.json({success:true,data:booking,notificationSent:false});if(booking.bookingStatus==="Cancelled"){booking.cancellationRequestedAt=booking.cancellationRequestedAt||new Date();if(!changedFields.includes("cancellationRequestedAt"))changedFields.push("cancellationRequestedAt");}await booking.save();try{await notifyBoth(booking,changedFields);}catch(emailErr){console.error("IMMEDIATE BOOKING UPDATE NOTIFICATION ERROR:",emailErr);}res.json({success:true,data:booking,notificationSent:true});}catch(err){console.error("ADMIN BOOKING UPDATE ERROR:",err);res.status(500).json({success:false,message:err.message||"Unable to update booking."});}});
module.exports=router;
