const express = require("express");
const router = express.Router();
const { requireAdmin } = require("../middleware/adminAuth");
const Setting = require("../models/Setting");
const {TEMPLATE_KEYS,mergedEmailNotificationDesign,sanitizeEmailNotificationDesign,invalidateEmailDesignCache}=require("../services/emailNotificationDesign");
async function getSettings(){let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});return settings;}
function host(settings){const booking=settings.guestBookingPage&&typeof settings.guestBookingPage==="object"?settings.guestBookingPage:{};return{booking,design:booking.emailNotificationDesign||{}};}
router.get("/", requireAdmin, async (req,res)=>{try{const settings=await getSettings(),h=host(settings);res.set("Cache-Control","no-store");res.json({success:true,templateKeys:TEMPLATE_KEYS,data:mergedEmailNotificationDesign(h.design)});}catch(err){console.error("EMAIL DESIGN GET ERROR:",err);res.status(500).json({success:false,message:"Unable to load email notification design."});}});
router.put("/", requireAdmin, async (req,res)=>{try{const clean=sanitizeEmailNotificationDesign(req.body||{}),settings=await getSettings(),h=host(settings),current=mergedEmailNotificationDesign(h.design),next={...current,...clean,templates:{...current.templates,...(clean.templates||{})},version:1};settings.guestBookingPage={...h.booking,emailNotificationDesign:next};settings.markModified("guestBookingPage");await settings.save();invalidateEmailDesignCache();res.json({success:true,message:"Email notification design saved.",data:mergedEmailNotificationDesign(next)});}catch(err){console.error("EMAIL DESIGN UPDATE ERROR:",err);const status=/^Invalid /.test(String(err.message||""))?400:500;res.status(status).json({success:false,message:err.message||"Unable to save email notification design."});}});
router.post("/reset", requireAdmin, async (req,res)=>{try{const settings=await getSettings(),h=host(settings);const next={...h.booking};delete next.emailNotificationDesign;settings.guestBookingPage=next;settings.markModified("guestBookingPage");await settings.save();invalidateEmailDesignCache();res.json({success:true,message:"Email notification design restored.",data:mergedEmailNotificationDesign({})});}catch(err){res.status(500).json({success:false,message:"Unable to reset email notification design."});}});
module.exports=router;
