const express = require("express");
const multer = require("multer");
const path = require("path");
const jwt = require("jsonwebtoken");
const Booking = require("../models/Booking");
const GuestAccount = require("../models/GuestAccount");
const Notification = require("../models/Notification");
const { saveBuffer, openDownload } = require("../services/gridfsStorage");
const router = express.Router();
const storage = multer.memoryStorage();
const upload=multer({storage,limits:{fileSize:10*1024*1024},fileFilter(req,file,cb){const allowed=["image/jpeg","image/png","image/webp","application/pdf"];if(!allowed.includes(file.mimetype))return cb(new Error("Documents must be JPG, PNG, WEBP, or PDF."));cb(null,true);}});
const ADMIN_EMAIL = String(process.env.ADMIN_EMAIL || process.env.EMAIL_USER || "casmartstaycation@gmail.com").trim().toLowerCase();
function guestFromToken(req){const header=req.headers.authorization||"";if(!header.startsWith("Bearer "))throw new Error("Authentication required.");return jwt.verify(header.slice(7),process.env.JWT_SECRET||"ca-smart-staycation-guest-secret");}
async function notifyBoth(booking,{title,message,type}){const guestEmail=String(booking.email||"").trim().toLowerCase();const docs=[];if(guestEmail)docs.push({recipientType:"guest",recipientEmail:guestEmail,booking:booking._id,title,message,type});docs.push({recipientType:"admin",recipientEmail:ADMIN_EMAIL,booking:booking._id,title,message,type});await Notification.insertMany(docs);}
async function saveFile(file, bookingId, field){if(!file)return "";const safeRef=String(bookingId||"booking").replace(/[^a-zA-Z0-9_-]/g,"");const filename=`${safeRef}-${field}-${Date.now()}${path.extname(file.originalname).toLowerCase()}`;return saveBuffer(file.buffer,filename,file.mimetype);}
function streamFile(id,res){const stream=openDownload(id);if(!stream)return res.status(404).send("Document not found.");stream.on("file",file=>{if(file.contentType)res.type(file.contentType);});stream.on("error",()=>{if(!res.headersSent)res.status(404).send("Document not found.");});stream.pipe(res);}
router.post("/bookings/:id/reschedule-payment",upload.single("reschedulePaymentProof"),async(req,res)=>{try{const payload=guestFromToken(req),account=await GuestAccount.findById(payload.accountId).lean(),booking=await Booking.findById(req.params.id);if(!account)return res.status(401).json({success:false,message:"Account not found."});if(!booking)return res.status(404).json({success:false,message:"Booking not found."});if(String(booking.email||"").trim().toLowerCase()!==String(account.email||"").trim().toLowerCase())return res.status(403).json({success:false,message:"You are not allowed to update this booking."});if(!booking.reschedulePending||!booking.reschedulePendingCheckIn||!booking.reschedulePendingCheckOut)return res.status(409).json({success:false,message:"There is no pending date-change request for this booking."});if(booking.reschedulePaymentStatus==="Pending Verification")return res.status(409).json({success:false,message:"Your convenience-fee payment proof is already waiting for admin verification."});if(!req.file)return res.status(400).json({success:false,message:"Proof of payment for the convenience fee is required."});booking.reschedulePaymentProof=await saveFile(req.file,booking._id,"reschedulePaymentProof");booking.reschedulePaymentSubmittedAt=new Date();booking.reschedulePaymentStatus="Pending Verification";await booking.save();await notifyBoth(booking,{title:`Date-Change Payment Proof Uploaded — ${booking.bookingReference}`,message:`Payment proof for the date-change convenience fee was uploaded. The request is pending admin verification.`,type:"reschedule-payment-proof"});res.json({success:true,message:`Proof of payment uploaded successfully. Your date-change request for ${new Date(booking.reschedulePendingCheckIn).toLocaleDateString("en-PH")} to ${new Date(booking.reschedulePendingCheckOut).toLocaleDateString("en-PH")} is now pending admin approval. The original booking dates remain active until approved.`,data:booking});}catch(err){console.error("RESCHEDULE PAYMENT UPLOAD ERROR:",err);if(err.name==="JsonWebTokenError"||err.name==="TokenExpiredError")return res.status(401).json({success:false,message:"Session expired or invalid."});res.status(400).json({success:false,message:err.message||"Convenience fee proof upload failed."});}});
router.post("/bookings/:id/documents",upload.fields([{name:"governmentId",maxCount:1},{name:"driversLicense",maxCount:1}]),async(req,res)=>{try{const booking=await Booking.findById(req.params.id);if(!booking)return res.status(404).json({success:false,message:"Booking not found."});const governmentId=req.files?.governmentId?.[0],driversLicense=req.files?.driversLicense?.[0];if(!governmentId&&!booking.governmentId&&!booking.parkingOnly)return res.status(400).json({success:false,message:"Government-issued ID is required."});if(booking.parking&&!driversLicense&&!booking.driversLicense)return res.status(400).json({success:false,message:"Driver's license is required for parking bookings."});if(governmentId)booking.governmentId=await saveFile(governmentId,booking._id,"governmentId");if(driversLicense)booking.driversLicense=await saveFile(driversLicense,booking._id,"driversLicense");booking.vehicleBrand=String(req.body.vehicleBrand||booking.vehicleBrand||"").trim();booking.vehicleModel=String(req.body.vehicleModel||booking.vehicleModel||"").trim();booking.vehicleColor=String(req.body.vehicleColor||booking.vehicleColor||"").trim();booking.plateNumber=String(req.body.plateNumber||booking.plateNumber||"").trim();await booking.save();const uploaded=[governmentId&&"Government ID",driversLicense&&"Driver's License"].filter(Boolean).join(" and ");await notifyBoth(booking,{title:`Guest Documents Uploaded — ${booking.bookingReference}`,message:`${uploaded||"Guest booking documents"} were uploaded/updated. Please review the documents in the booking account.`,type:"document-upload"});res.json({success:true,message:"Guest documents uploaded successfully.",data:{governmentId:booking.governmentId,driversLicense:booking.driversLicense,vehicleBrand:booking.vehicleBrand,vehicleModel:booking.vehicleModel,vehicleColor:booking.vehicleColor,plateNumber:booking.plateNumber}});}catch(err){console.error("GUEST DOCUMENT UPLOAD ERROR:",err);res.status(400).json({success:false,message:err.message||"Document upload failed."});}});
router.get("/bookings/:id/documents/:type",async(req,res)=>{try{const booking=await Booking.findById(req.params.id).lean();if(!booking)return res.status(404).send("Booking not found.");const field=req.params.type==="driversLicense"?"driversLicense":req.params.type==="governmentId"?"governmentId":req.params.type==="reschedulePaymentProof"?"reschedulePaymentProof":null;if(!field||!booking[field])return res.status(404).send("Document not found.");streamFile(booking[field],res);}catch(err){res.status(500).send("Unable to open document.");}});
module.exports=router;
