const express = require("express");
const jwt = require("jsonwebtoken");
const crypto = require("crypto");
const GuestAccount = require("../models/GuestAccount");
const Booking = require("../models/Booking");
const Notification = require("../models/Notification");
const Message = require("../models/Message");
const sendEmail = require("../mail/sendEmail");
const { saveBuffer, openDownload, getFileInfo } = require("../services/gridfsStorage");
const router = express.Router();
const JWT_SECRET = process.env.JWT_SECRET || "ca-smart-staycation-guest-secret";
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || process.env.EMAIL_USER || "casmartstaycation@gmail.com";
const ADMIN_PASSWORD = String(process.env.ADMIN_PASSWORD || "");
const ADMIN_JWT_SECRET = process.env.ADMIN_JWT_SECRET || process.env.JWT_SECRET || (ADMIN_PASSWORD ? crypto.createHash("sha256").update(`ca-smart-admin:${ADMIN_PASSWORD}`).digest("hex") : "");
function guestPayload(req){const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))throw new Error("Authentication required.");return jwt.verify(h.slice(7),JWT_SECRET)}
function adminPayload(req){const h=req.headers.authorization||"";if(!h.startsWith("Bearer ")||!ADMIN_JWT_SECRET)throw new Error("Admin authentication required.");const p=jwt.verify(h.slice(7),ADMIN_JWT_SECRET);if(p.role!=="admin"||String(p.email||"").toLowerCase()!==String(ADMIN_EMAIL).toLowerCase())throw new Error("Admin access required.");return p}
function normalizeAttachment(a){if(!a||typeof a!=="object")return null;const name=String(a.name||"Attachment").trim().slice(0,200);const data=typeof a.data==="string"?a.data.trim():typeof a.url==="string"?a.url.trim():"";let type=String(a.type||"").toLowerCase().trim();if(/^data:image\/(jpeg|jpg|png|webp|gif|bmp|svg\+xml);base64,/i.test(data))type=type||data.slice(5,data.indexOf(";"));if(/^data:application\/pdf;base64,/i.test(data))type=type||"application/pdf";if(type==="image/jpg")type="image/jpeg";if(!type){const ext=name.toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||"";type=({jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",webp:"image/webp",gif:"image/gif",bmp:"image/bmp",svg:"image/svg+xml",pdf:"application/pdf"})[ext]||""}const allowed=["image/jpeg","image/png","image/webp","image/gif","image/bmp","image/svg+xml","application/pdf"];if(!allowed.includes(type))return null;if(!/^data:[^;]+;base64,/i.test(data)&&!/^https?:\/\//i.test(data)&&!data.startsWith("/"))return null;if(data.length>7*1024*1024)return null;return{name,type,data}}
function getAttachments(body){const raw=Array.isArray(body?.attachments)?body.attachments:[];return raw.map(normalizeAttachment).filter(Boolean).slice(0,3)}
function attachmentBytes(list){return list.reduce((n,a)=>n+Buffer.byteLength(String(a.data||""),"utf8"),0)}
async function persistAttachments(list){const out=[];for(const a of list){if(/^data:[^;]+;base64,/i.test(a.data)){const comma=a.data.indexOf(",");const encoded=comma>=0?a.data.slice(comma+1):"";const buffer=Buffer.from(encoded,"base64");if(!buffer.length)continue;const fileId=await saveBuffer(buffer,a.name,a.type);out.push({name:a.name,type:a.type,data:"",fileId})}else if(a.data)out.push({name:a.name,type:a.type,data:a.data,fileId:""})}return out}
function attachmentToken(messageId,guestEmail){return jwt.sign({scope:"message-attachment",messageId:String(messageId),guestEmail:String(guestEmail||"").toLowerCase()},JWT_SECRET,{expiresIn:"1h"})}
function publicMessage(m){return{...m,attachments:(m.attachments||[]).map(a=>({name:a.name,type:a.type,url:a.fileId?`/api/messages/${m._id}/attachments/${encodeURIComponent(a.name)}?token=${encodeURIComponent(attachmentToken(m._id,m.guestEmail))}`:a.data||""}))}}
async function guestAccount(req){const p=guestPayload(req);const a=await GuestAccount.findById(p.accountId).lean();if(!a)throw new Error("Account not found.");return a}
async function safeEmail(to,subject,html){try{if(to)await sendEmail(String(to).trim().toLowerCase(),subject,html)}catch(e){console.error(`MESSAGE ACTION EMAIL FAILED (${to}):`,e.message)}}
async function syncCancellationNotifications(email){const cancelled=await Booking.find({email:String(email).trim().toLowerCase(),bookingStatus:"Cancelled",refundRequested:true}).lean();for(const b of cancelled){const exists=await Notification.exists({recipientType:"guest",recipientEmail:email,booking:b._id,type:"cancellation"});if(!exists)await Notification.create({recipientType:"guest",recipientEmail:email,booking:b._id,title:"Booking cancelled and refund requested",message:`Booking ${b.bookingReference} was cancelled. Refund requested: ₱${Number(b.refundAmount||0).toLocaleString()}. Refund status: ${b.refundStatus||"Requested"}.`,type:"cancellation"})}}
async function syncAdminCancellationNotifications(){const cancelled=await Booking.find({bookingStatus:"Cancelled",refundRequested:true}).lean();for(const b of cancelled){const exists=await Notification.exists({recipientType:"admin",booking:b._id,type:"cancellation"});if(!exists)await Notification.create({recipientType:"admin",booking:b._id,title:"Booking cancellation — refund required",message:`${b.bookingReference} was cancelled by the guest. Refund due: ₱${Number(b.refundAmount||0).toLocaleString()}.`,type:"cancellation"})}}
router.get("/guest/inbox",async(req,res)=>{try{const a=await guestAccount(req);await syncCancellationNotifications(a.email);const [messages,notifications]=await Promise.all([Message.find({guestEmail:a.email}).sort({createdAt:1}).lean(),Notification.find({recipientType:"guest",recipientEmail:a.email}).sort({createdAt:-1}).lean()]);res.json({success:true,messages:messages.map(publicMessage),notifications})}catch(e){res.status(401).json({success:false,message:e.message})}});
router.get("/admin/inbox",async(req,res)=>{try{adminPayload(req);await syncAdminCancellationNotifications();const [messages,notifications]=await Promise.all([Message.find().sort({createdAt:1}).populate("booking").lean(),Notification.find({recipientType:"admin"}).sort({createdAt:-1}).lean()]);res.json({success:true,messages:messages.map(publicMessage),notifications})}catch(e){res.status(401).json({success:false,message:e.message})}});
router.get("/messages/:messageId/attachments/:name",async(req,res)=>{try{const queryToken=String(req.query.token||"");let tokenPayload=null;if(queryToken){tokenPayload=jwt.verify(queryToken,JWT_SECRET);if(tokenPayload.scope!=="message-attachment"||String(tokenPayload.messageId)!==String(req.params.messageId))return res.status(403).json({success:false,message:"Attachment access denied."})}else{try{adminPayload(req)}catch(_){const a=await guestAccount(req);const check=await Message.findById(req.params.messageId).select("guestEmail").lean();if(!check||String(check.guestEmail).toLowerCase()!==String(a.email).toLowerCase())return res.status(403).json({success:false,message:"Attachment access denied."})}}const message=await Message.findById(req.params.messageId).lean();if(!message)return res.status(404).json({success:false,message:"Message not found."});if(tokenPayload&&tokenPayload.guestEmail&&String(message.guestEmail).toLowerCase()!==String(tokenPayload.guestEmail).toLowerCase())return res.status(403).json({success:false,message:"Attachment access denied."});const attachment=(message.attachments||[]).find(a=>String(a.name)===String(req.params.name));if(!attachment)return res.status(404).json({success:false,message:"Attachment not found."});if(!attachment.fileId){if(!attachment.data)return res.status(404).end();const comma=attachment.data.indexOf(",");const encoded=comma>=0?attachment.data.slice(comma+1):"";const buffer=Buffer.from(encoded,"base64");res.setHeader("Content-Type",attachment.type||"application/octet-stream");res.setHeader("Content-Disposition",`inline; filename="${String(attachment.name).replace(/"/g,"'")}"`);return res.end(buffer)}const info=await getFileInfo(attachment.fileId);if(!info)return res.status(404).json({success:false,message:"Stored attachment not found."});res.setHeader("Content-Type",info.contentType||attachment.type||"application/octet-stream");res.setHeader("Content-Disposition",`inline; filename="${String(attachment.name).replace(/"/g,"'")}"`);const stream=openDownload(attachment.fileId);if(!stream)return res.status(404).end();stream.on("error",()=>{if(!res.headersSent)res.status(404).end();else res.end()});stream.pipe(res)}catch(e){console.error("MESSAGE ATTACHMENT ERROR",e);res.status(401).json({success:false,message:e.message})}});
router.put("/guest/inbox/read",async(req,res)=>{try{const a=await guestAccount(req);await Promise.all([Message.updateMany({guestEmail:a.email,readByGuest:false},{$set:{readByGuest:true}}),Notification.updateMany({recipientType:"guest",recipientEmail:a.email,read:false},{$set:{read:true}})]);res.json({success:true})}catch(e){res.status(401).json({success:false,message:e.message})}});
router.post("/guest/messages",async(req,res)=>{try{const a=await guestAccount(req);const text=String(req.body.message||"").trim();const raw=getAttachments(req.body);if(!text&&!raw.length)return res.status(400).json({success:false,message:"Enter a message or attach a file."});if(attachmentBytes(raw)>5.5*1024*1024)return res.status(413).json({success:false,message:"The selected attachments are too large. Please use smaller photos."});const attachments=await persistAttachments(raw);if(raw.length&&!attachments.length)return res.status(400).json({success:false,message:"The selected attachment could not be stored."});let booking=null;if(req.body.bookingId){booking=await Booking.findById(req.body.bookingId).lean();if(!booking||String(booking.email).toLowerCase()!==String(a.email).toLowerCase())return res.status(403).json({success:false,message:"Booking not found for this account."})}const m=await Message.create({guestEmail:a.email,booking:booking?booking._id:null,senderType:"guest",senderName:String(a.email).split("@")[0],message:text,attachments,readByGuest:true,readByAdmin:false});await Notification.create({recipientType:"admin",title:"New guest message",message:`${a.email} sent a new message${booking?` about ${booking.bookingReference}`:""}.`,type:"message",booking:booking?booking._id:null});await safeEmail(ADMIN_EMAIL,`New Guest Message${booking?` — ${booking.bookingReference}`:""}`,`<h2>CA Smart Staycation Admin Notification</h2><p><strong>Guest:</strong> ${a.email}</p><p><strong>Message:</strong></p><p>${String(text||"(Attachment only)").replace(/</g,"&lt;")}</p><p>The guest message is available in the Admin Message Inbox.</p>`);res.status(201).json({success:true,data:publicMessage(m.toObject())})}catch(e){console.error("GUEST MESSAGE ERROR",e);res.status(400).json({success:false,message:e.message})}});
router.put("/admin/inbox/read",async(req,res)=>{try{adminPayload(req);await Promise.all([Message.updateMany({readByAdmin:false},{$set:{readByAdmin:true}}),Notification.updateMany({recipientType:"admin",read:false},{$set:{read:true}})]);res.json({success:true})}catch(e){res.status(401).json({success:false,message:e.message})}});
router.post("/admin/messages",async(req,res)=>{try{adminPayload(req);const email=String(req.body.guestEmail||"").trim().toLowerCase();const text=String(req.body.message||"").trim();const raw=getAttachments(req.body);if(!email||(!text&&!raw.length))return res.status(400).json({success:false,message:"Guest email and message or attachment are required."});if(attachmentBytes(raw)>5.5*1024*1024)return res.status(413).json({success:false,message:"The selected attachments are too large. Please use smaller photos."});const attachments=await persistAttachments(raw);if(raw.length&&!attachments.length)return res.status(400).json({success:false,message:"The selected attachment could not be stored."});const booking=req.body.bookingId?await Booking.findById(req.body.bookingId).lean():null;const m=await Message.create({guestEmail:email,booking:booking?booking._id:null,senderType:"admin",senderName:"CA Smart Staycation Admin",message:text,attachments,readByGuest:false,readByAdmin:true});await Notification.create({recipientType:"guest",recipientEmail:email,title:"New message from CA Smart Staycation",message:(text||"Attachment").slice(0,180),type:"message",booking:booking?booking._id:null});await safeEmail(email,`New message from CA Smart Staycation${booking?` — ${booking.bookingReference}`:""}`,`<h2>CA Smart Staycation</h2><p>You have a new message from CA Smart Staycation.</p><p><strong>Message:</strong></p><p>${String(text||"(Attachment included)").replace(/</g,"&lt;")}</p><p>Please log in to your Guest Account to view and reply.</p>`);res.status(201).json({success:true,data:publicMessage(m.toObject())})}catch(e){console.error("ADMIN MESSAGE ERROR",e);res.status(400).json({success:false,message:e.message})}});
router.post("/admin/bookings/:id/refund",async(req,res)=>{try{adminPayload(req);const booking=await Booking.findById(req.params.id);if(!booking)return res.status(404).json({success:false,message:"Booking not found."});if(!booking.refundRequested)return res.status(409).json({success:false,message:"This booking has no refund request."});if(booking.refundStatus==="Refunded")return res.status(409).json({success:false,message:"This refund has already been processed."});booking.refundStatus="Refunded";booking.paymentStatus="Refunded";booking.refundProcessedAt=new Date();booking.refundProcessedBy=ADMIN_EMAIL;await booking.save();const message=`Refund for booking ${booking.bookingReference} has been processed. Refund amount: ₱${Number(booking.refundAmount||0).toLocaleString()}.`;await Notification.create({recipientType:"guest",recipientEmail:booking.email,booking:booking._id,title:"Refund processed",message,type:"refund"});await Notification.create({recipientType:"admin",recipientEmail:ADMIN_EMAIL,booking:booking._id,title:`Refund processed — ${booking.bookingReference}`,message,type:"refund"});await safeEmail(booking.email,`Refund Processed — ${booking.bookingReference}`,`<h2>CA Smart Staycation</h2><p>${message}</p><p>Please log in to your Guest Account for the complete booking record.</p>`);res.json({success:true,message:"Refund marked as processed and notifications sent.",data:booking})}catch(e){console.error("ADMIN REFUND ERROR",e);res.status(401).json({success:false,message:e.message})}});
module.exports=router;
