console.log("🔥 settingsRoutes.js executed");
const express = require("express");
const router = express.Router();
const { requireAdmin } = require("../middleware/adminAuth");
const Setting = require("../models/Setting");
const Booking = require("../models/Booking");
router.get("/test", (req, res) => res.json({ status: "success", message: "Settings router loaded" }));
const validEmail = email => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
const DEFAULT_ADMIN_NOTIFICATION_EMAIL = "casmartstaycation@gmail.com";
const LEGACY_DEFAULT_ADMIN_NOTIFICATION_EMAIL = "markryantamayo@gmail.com";
const TERMINAL_BOOKING_STATUSES = ["Cancelled", "Checked Out", "Expired"];
const validDateKey = value => /^\d{4}-\d{2}-\d{2}$/.test(String(value || ""));

router.get("/", async (req, res) => { let settings = await Setting.findOne(); if (!settings) settings = await Setting.create({}); res.json({ status: "success", data: settings }); });
router.put("/", async (req, res) => { const safeBody={...(req.body||{})};delete safeBody.guestBookingPage;delete safeBody.guestAccountPage;let settings = await Setting.findOne(); if (!settings) settings = await Setting.create(safeBody); else { Object.assign(settings, safeBody); await settings.save(); } res.json({ status: "success", data: settings }); });

router.get("/admin-notification-email", requireAdmin, async (req, res) => {
  try { let settings=await Setting.findOne(); if(!settings)settings=await Setting.create({}); const fallback=process.env.ADMIN_EMAIL||process.env.EMAIL_USER||DEFAULT_ADMIN_NOTIFICATION_EMAIL; const configuredEmail=String(settings.adminNotificationEmail||"").trim().toLowerCase(); const primary=configuredEmail===LEGACY_DEFAULT_ADMIN_NOTIFICATION_EMAIL||!configuredEmail?fallback:configuredEmail; if(configuredEmail===LEGACY_DEFAULT_ADMIN_NOTIFICATION_EMAIL){settings.adminNotificationEmail=fallback;await settings.save();} const emails=Array.from(new Set([primary,...(settings.adminNotificationEmails||[])].filter(validEmail))); res.json({success:true,email:primary,emails,adminContactNumber:String(settings.adminContactNumber||"")}); }
  catch(err){console.error("ADMIN NOTIFICATION EMAIL GET ERROR:",err);res.status(500).json({success:false,message:"Unable to load admin account settings."});}
});
router.put("/admin-notification-email", requireAdmin, async (req,res)=>{try{const email=String(req.body?.email||"").trim().toLowerCase();if(!validEmail(email))return res.status(400).json({success:false,message:"Please provide a valid email address."});let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});settings.adminNotificationEmail=email;await settings.save();res.json({success:true,email});}catch(err){console.error("ADMIN NOTIFICATION EMAIL UPDATE ERROR:",err);res.status(500).json({success:false,message:"Unable to save admin notification email."});}});
router.put("/admin-contact", requireAdmin, async (req,res)=>{try{const contact=String(req.body?.contactNumber||"").trim();if(contact.length>40)return res.status(400).json({success:false,message:"Contact number is too long."});let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});settings.adminContactNumber=contact;await settings.save();res.json({success:true,adminContactNumber:settings.adminContactNumber});}catch(err){console.error("ADMIN CONTACT UPDATE ERROR:",err);res.status(500).json({success:false,message:"Unable to save admin contact number."});}});
router.put("/admin-notification-emails", requireAdmin, async (req,res)=>{try{const input=Array.isArray(req.body?.emails)?req.body.emails:[];const emails=Array.from(new Set(input.map(v=>String(v||"").trim().toLowerCase()).filter(Boolean)));if(emails.length>20)return res.status(400).json({success:false,message:"You can add up to 20 admin notification emails."});const invalid=emails.find(email=>!validEmail(email));if(invalid)return res.status(400).json({success:false,message:`Invalid email address: ${invalid}`});let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});const primary=settings.adminNotificationEmail||process.env.ADMIN_EMAIL||process.env.EMAIL_USER||DEFAULT_ADMIN_NOTIFICATION_EMAIL;settings.adminNotificationEmails=Array.from(new Set([primary,...emails].filter(validEmail)));await settings.save();res.json({success:true,emails:settings.adminNotificationEmails});}catch(err){console.error("ADMIN NOTIFICATION EMAILS UPDATE ERROR:",err);res.status(500).json({success:false,message:"Unable to save admin notification emails."});}});
router.delete("/admin-notification-emails", requireAdmin, async (req,res)=>{try{const email=String(req.body?.email||"").trim().toLowerCase();let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});settings.adminNotificationEmails=(settings.adminNotificationEmails||[]).filter(v=>v.toLowerCase()!==email);await settings.save();res.json({success:true,emails:settings.adminNotificationEmails});}catch(err){console.error("ADMIN NOTIFICATION EMAIL DELETE ERROR:",err);res.status(500).json({success:false,message:"Unable to remove admin notification email."});}});

router.get("/admin-blocked-dates", requireAdmin, async (req,res)=>{try{let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});const blockedDates=[...(settings.blockedDates||[])].sort((a,b)=>String(a.date).localeCompare(String(b.date)));res.json({success:true,data:blockedDates});}catch(err){console.error("ADMIN BLOCKED DATES GET ERROR:",err);res.status(500).json({success:false,message:"Unable to load blocked dates."});}});
router.post("/admin-blocked-dates", requireAdmin, async (req,res)=>{try{const date=String(req.body?.date||"").trim();const reason=String(req.body?.reason||"Maintenance").trim().slice(0,80)||"Maintenance";if(!validDateKey(date))return res.status(400).json({success:false,message:"Please select a valid date."});const start=new Date(`${date}T00:00:00.000Z`);if(Number.isNaN(start.getTime()))return res.status(400).json({success:false,message:"Please select a valid date."});const end=new Date(start.getTime()+86400000);const conflict=await Booking.findOne({room:{$ne:null},parkingOnly:{$ne:true},bookingStatus:{$nin:TERMINAL_BOOKING_STATUSES},checkIn:{$lt:end},checkOut:{$gt:start}}).select("bookingReference").lean();if(conflict)return res.status(409).json({success:false,message:`Cannot block ${date} because booking ${conflict.bookingReference||"an active booking"} already uses this date.`});let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});const existing=(settings.blockedDates||[]).find(item=>String(item.date)===date);if(existing){existing.reason=reason;existing.createdAt=new Date();}else settings.blockedDates.push({date,reason,createdAt:new Date()});await settings.save();res.json({success:true,message:`${date} is now blocked for accommodation bookings.`,data:settings.blockedDates});}catch(err){console.error("ADMIN BLOCK DATE ERROR:",err);res.status(500).json({success:false,message:"Unable to block this date."});}});
router.delete("/admin-blocked-dates/:date", requireAdmin, async (req,res)=>{try{const date=String(req.params.date||"").trim();if(!validDateKey(date))return res.status(400).json({success:false,message:"Invalid blocked date."});let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});settings.blockedDates=(settings.blockedDates||[]).filter(item=>String(item.date)!==date);await settings.save();res.json({success:true,message:`${date} is available again.`,data:settings.blockedDates});}catch(err){console.error("ADMIN UNBLOCK DATE ERROR:",err);res.status(500).json({success:false,message:"Unable to unblock this date."});}});

router.get("/admin-parking-blocked-dates", requireAdmin, async (req,res)=>{try{let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});const blockedDates=[...(settings.parkingBlockedDates||[])].sort((a,b)=>String(a.date).localeCompare(String(b.date)));res.json({success:true,data:blockedDates});}catch(err){console.error("ADMIN PARKING BLOCKED DATES GET ERROR:",err);res.status(500).json({success:false,message:"Unable to load parking blocked dates."});}});
router.post("/admin-parking-blocked-dates", requireAdmin, async (req,res)=>{try{const date=String(req.body?.date||"").trim();const reason=String(req.body?.reason||"Maintenance").trim().slice(0,80)||"Maintenance";if(!validDateKey(date))return res.status(400).json({success:false,message:"Please select a valid date."});const start=new Date(`${date}T00:00:00.000Z`);if(Number.isNaN(start.getTime()))return res.status(400).json({success:false,message:"Please select a valid date."});const end=new Date(start.getTime()+86400000);const conflict=await Booking.findOne({parking:{$ne:null},bookingStatus:{$nin:TERMINAL_BOOKING_STATUSES},checkIn:{$lt:end},checkOut:{$gt:start}}).select("bookingReference").lean();if(conflict)return res.status(409).json({success:false,message:`Cannot block parking on ${date} because booking ${conflict.bookingReference||"an active booking"} already uses parking on this date.`});let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});const existing=(settings.parkingBlockedDates||[]).find(item=>String(item.date)===date);if(existing){existing.reason=reason;existing.createdAt=new Date();}else settings.parkingBlockedDates.push({date,reason,createdAt:new Date()});await settings.save();res.json({success:true,message:`Parking is now blocked on ${date}.`,data:settings.parkingBlockedDates});}catch(err){console.error("ADMIN PARKING BLOCK DATE ERROR:",err);res.status(500).json({success:false,message:"Unable to block parking on this date."});}});
router.delete("/admin-parking-blocked-dates/:date", requireAdmin, async (req,res)=>{try{const date=String(req.params.date||"").trim();if(!validDateKey(date))return res.status(400).json({success:false,message:"Invalid parking blocked date."});let settings=await Setting.findOne();if(!settings)settings=await Setting.create({});settings.parkingBlockedDates=(settings.parkingBlockedDates||[]).filter(item=>String(item.date)!==date);await settings.save();res.json({success:true,message:`Parking is available again on ${date}.`,data:settings.parkingBlockedDates});}catch(err){console.error("ADMIN PARKING UNBLOCK DATE ERROR:",err);res.status(500).json({success:false,message:"Unable to unblock parking on this date."});}});

router.use("/guest-account-design", require("./guestAccountDesignRoutes"));
router.use("/page-design", require("./pageDesignRoutes"));

module.exports = router;
