/* =========================================
   CA SMART STAYCATION
   GUEST BOOKING WEBSITE
========================================= */

// Use the same-origin API. The page is served from www.casmartstaycation.com,
// so relative /api requests avoid the apex→www 308 redirect and CORS entirely.
const API = "/api";
const governmentIdInput = document.getElementById("governmentId");
const governmentIdName = document.getElementById("governmentIdName");
if (governmentIdInput && governmentIdName) governmentIdInput.addEventListener("change", function () { governmentIdName.textContent = this.files?.length ? this.files[0].name : "No file selected"; });

let settings = { extraAdultFee: 300, parkingRate: 500, securityDeposit: 1000 };
let rooms = [];
let parkingSlots = [];
let selectedParkingId = null;
let selectedParkingNumber = null;
let bookedDates = [];
let currentDate = new Date();
let currentMonth = currentDate.getMonth();
let currentYear = currentDate.getFullYear();
let selectedCheckIn = null;
let selectedCheckOut = null;
let availabilityLoaded = false;
let availabilityLoading = null;

function formatLocalDate(date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function parseBookingDate(value) { if (!value) return null; const s=String(value); if(/^\d{4}-\d{2}-\d{2}/.test(s)){const p=s.slice(0,10).split("-").map(Number);return new Date(p[0],p[1]-1,p[2]);} return null; }
function isTerminalBooking(b) { return ["cancelled","checked out","expired"].includes(String(b?.bookingStatus||"").trim().toLowerCase()); }
function idOf(value) { if (!value) return ""; if (typeof value === "object") return String(value._id || value.id || ""); return String(value); }
function bookingHasAccommodation(b) { return !!idOf(b?.room) || !!idOf(b?.unit); }
function bookingHasParking(b) { if (!b) return false; if (b.parkingOnly === true || String(b.parkingOnly).toLowerCase() === "true") return true; if (idOf(b.parking) || idOf(b.parkingSlot) || !!String(b.parkingNumber||"").trim()) return true; return false; }
function datesOverlap(target,start,end){return !!(start&&end&&target>=start&&target<end);}
function bookingOverlapsDates(b,start,end){const s=parseBookingDate(b?.checkIn),e=parseBookingDate(b?.checkOut);return !!(s&&e&&start&&end&&start<e&&end>s);}
function setMinimumDates(){const a=document.getElementById("checkIn"),b=document.getElementById("checkOut");if(!a||!b)return;const t=new Date();t.setHours(0,0,0,0);a.min=formatLocalDate(t);b.min=formatLocalDate(t);}

document.addEventListener("DOMContentLoaded",async()=>{try{setMinimumDates();await loadSettings();await loadRooms();await loadParkingSlots();await loadBookedDates();setupEvents();const form=document.getElementById("guestBookingForm");if(form)form.addEventListener("submit",submitBooking);}catch(err){console.error(err);}});
window.addEventListener("load",renderCalendar);
async function loadSettings(){try{const r=await fetch(`${API}/settings`,{cache:"no-store"}),j=await r.json();if(r.ok&&j.data)settings={...settings,...j.data};}catch(e){console.warn("Unable to load settings. Using defaults.");}}
async function loadRooms(){try{const r=await fetch(`${API}/rooms`,{cache:"no-store",headers:{Accept:"application/json"}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||`Rooms load failed`);rooms=Array.isArray(j.data)?j.data:[];const roomSelect=document.getElementById("room");if(roomSelect){roomSelect.innerHTML='<option value="">Select Accommodation</option>';rooms.forEach(room=>{const opt=document.createElement("option");opt.value=idOf(room);opt.textContent=`${room.unitNumber||room.roomNumber||""} - ${room.unitName||room.roomName||"Room"}`;roomSelect.appendChild(opt);})}}catch(err){console.error("GET ROOMS ERROR:",err);rooms=[];}}
async function loadParkingSlots(){try{const r=await fetch(`${API}/parking`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.message||"Unable to load parking slots.");parkingSlots=Array.isArray(j.data)?j.data:[];const parkingSelect=document.getElementById("parking");if(parkingSelect){parkingSelect.innerHTML='<option value="">Select Parking Slot</option>';parkingSlots.forEach(slot=>{const opt=document.createElement("option");opt.value=idOf(slot);opt.textContent=`${slot.parkingNumber||""} - ${slot.parkingName||"Parking"}`;parkingSelect.appendChild(opt);})}}catch(err){console.error("GET PARKING SLOTS ERROR:",err);parkingSlots=[];}}
async function loadBookedDates(force=false){if(availabilityLoading)return availabilityLoading;if(availabilityLoaded&&!force)return true;availabilityLoading=(async()=>{try{const r=await fetch(`${API}/bookings`,{cache:"no-store"}),j=await r.json();if(r.ok&&Array.isArray(j.data))bookedDates=j.data.filter(b=>!isTerminalBooking(b));else bookedDates=[];availabilityLoaded=true;return true;}catch(err){console.error("Failed to load booked dates:",err);bookedDates=[];availabilityLoaded=true;return false;}finally{availabilityLoading=null;}})();return availabilityLoading;}
function refreshAvailability(){availabilityLoaded=false;return loadBookedDates(true);}

document.addEventListener("visibilitychange",()=>{if(!document.hidden)renderCalendar();});
window.addEventListener("focus",()=>renderCalendar());

function setupEvents(){const room=document.getElementById("room"),guests=document.getElementById("guests"),parking=document.getElementById("parking"),type=document.getElementById("bookingType");room?.addEventListener("change",()=>{calculateTotal();renderCalendar();});guests?.addEventListener("change",calculateTotal);parking?.addEventListener("change",()=>{selectedParkingId=parking.value;selectedParkingNumber=parkingSlots.find(s=>idOf(s)===parking.value)?.parkingNumber||null;calculateTotal();renderCalendar();});type?.addEventListener("change",bookingTypeChanged);}
function bookingTypeChanged(){const type=String(document.getElementById("bookingType")?.value||"unit").trim().toLowerCase().replace(/[\s_-]/g,""),room=document.getElementById("room"),guests=document.getElementById("guests"),children=document.getElementById("children"),vehicleSection=document.getElementById("vehicleSection"),bookingNotes=document.getElementById("bookingNotes"),roomGroup=document.getElementById("roomGroup"),parkingGroup=document.getElementById("parkingGroup"),govIdSection=document.getElementById("governmentIdSection"),govIdInput=document.getElementById("governmentId");if(type==="parking"){room.value="";room.disabled=true;guests.value=2;guests.disabled=true;children.value=0;children.disabled=true;if(vehicleSection)vehicleSection.style.display="block";if(bookingNotes)bookingNotes.style.display="none";if(roomGroup)roomGroup.style.display="none";if(parkingGroup)parkingGroup.style.display="block";if(govIdSection)govIdSection.style.display="block";if(govIdInput)govIdInput.required=true;}else if(type==="both"){room.disabled=false;guests.disabled=false;children.disabled=false;if(vehicleSection)vehicleSection.style.display="block";if(bookingNotes)bookingNotes.style.display="block";if(roomGroup)roomGroup.style.display="block";if(parkingGroup)parkingGroup.style.display="block";if(govIdSection)govIdSection.style.display="block";if(govIdInput)govIdInput.required=true;}else{room.disabled=false;guests.disabled=false;children.disabled=false;if(vehicleSection)vehicleSection.style.display="none";if(bookingNotes)bookingNotes.style.display="block";if(roomGroup)roomGroup.style.display="block";if(parkingGroup)parkingGroup.style.display="block";if(govIdSection)govIdSection.style.display="block";if(govIdInput)govIdInput.required=true;}calculateTotal();renderCalendar();}

function calculateTotal(){const type=String(document.getElementById("bookingType")?.value||"unit").trim().toLowerCase().replace(/[\s_-]/g,""),roomId=document.getElementById("room")?.value,checkIn=parseBookingDate(document.getElementById("checkIn")?.value),checkOut=parseBookingDate(document.getElementById("checkOut")?.value),adults=Number(document.getElementById("guests")?.value||2),children=Number(document.getElementById("children")?.value||0);let roomAmount=0,extraGuestAmount=0,parkingAmount=0,totalAmount=0;if(roomId&&checkIn&&checkOut&&checkOut>checkIn){const room=rooms.find(r=>idOf(r)===roomId);if(room){const nights=Math.ceil((checkOut-checkIn)/86400000);roomAmount=room.price*nights;const extraAdults=Math.max(0,adults-2);extraGuestAmount=extraAdults*settings.extraAdultFee*nights;}}if(document.getElementById("parking")?.value){parkingAmount=(settings.parkingRate||500)*(Math.ceil((checkOut-checkIn)/86400000)||1);}totalAmount=roomAmount+extraGuestAmount+parkingAmount+settings.securityDeposit;updateSummary(roomAmount,extraGuestAmount,parkingAmount,settings.securityDeposit,totalAmount);}
function updateSummary(a,b,c,d,e){[["roomAmount",a],["extraGuestAmount",b],["parkingAmount",c],["securityDepositAmount",d],["totalAmount",e]].forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent="₱"+Number(v).toLocaleString("en-PH",{minimumFractionDigits:2,maximumFractionDigits:2});});}
function isDateBooked(date){const type=String(document.getElementById("bookingType")?.value||"unit").trim().toLowerCase().replace(/[\s_-]/g,""),selectedRoom=String(document.getElementById("room")?.value||"").trim(),selectedParking=String(document.getElementById("parking")?.value||"").trim();if(!date)return false;for(const booking of bookedDates){if(!bookingOverlapsDates(booking,date,new Date(date.getTime()+86400000)))continue;if(type==="parking"||(!selectedRoom&&type!=="both")){if(bookingHasParking(booking)&&(!selectedParking||idOf(booking.parking)===selectedParking))return true;}else if(selectedRoom){if(bookingHasAccommodation(booking)&&idOf(booking.room)===selectedRoom)return true;}if(type==="both"&&selectedParking&&bookingHasParking(booking)&&idOf(booking.parking)===selectedParking)return true;if(bookingHasAccommodation(booking)&&bookingHasParking(booking)){if(!selectedRoom&&selectedParking&&idOf(booking.parking)===selectedParking)return true;if(selectedRoom&&!selectedParking&&idOf(booking.room)===selectedRoom)return true;if(selectedRoom&&selectedParking&&(idOf(booking.room)===selectedRoom||idOf(booking.parking)===selectedParking))return true;}}return false;}
function renderCalendar(){const grid=document.getElementById("calendarGrid"),title=document.getElementById("calendarTitle");if(!grid||!title)return;grid.innerHTML="";const first=new Date(currentYear,currentMonth,1),last=new Date(currentYear,currentMonth+1,0);title.textContent=first.toLocaleString("en-US",{month:"long",year:"numeric"});const startDay=first.getDay(),today=new Date();today.setHours(0,0,0,0);for(let i=0;i<startDay;i++){const empty=document.createElement("div");empty.className="calendar-day empty";grid.appendChild(empty);}for(let day=1;day<=last.getDate();day++){const date=new Date(currentYear,currentMonth,day);date.setHours(0,0,0,0);const cell=document.createElement("div");cell.className="calendar-day";cell.textContent=day;if(date<today){cell.classList.add("disabled");}else if(isDateBooked(date)){cell.classList.add("booked");cell.title="Already booked";}else{cell.addEventListener("click",()=>{if(!selectedCheckIn||selectedCheckOut){selectedCheckIn=new Date(date);selectedCheckOut=null;}else{if(date>selectedCheckIn){let blocked=false;const temp=new Date(selectedCheckIn);temp.setDate(temp.getDate()+1);while(temp<date){if(isDateBooked(temp)){blocked=true;break;}temp.setDate(temp.getDate()+1);}if(blocked){alert("Your selected stay contains booked dates. Please choose another date range.");selectedCheckIn=null;selectedCheckOut=null;document.getElementById("checkIn").value="";document.getElementById("checkOut").value="";renderCalendar();return;}selectedCheckOut=new Date(date);}else{selectedCheckIn=new Date(date);selectedCheckOut=null;}}document.getElementById("checkIn").value=selectedCheckIn.toISOString().split("T")[0];document.getElementById("checkOut").value=selectedCheckOut?selectedCheckOut.toISOString().split("T")[0]:"";calculateTotal();renderCalendar();});}if(selectedCheckIn&&date.getTime()===selectedCheckIn.getTime()){cell.classList.add("checkin");}if(selectedCheckOut&&date.getTime()===selectedCheckOut.getTime()){cell.classList.add("checkout");}if(selectedCheckIn&&selectedCheckOut&&date>selectedCheckIn&&date<selectedCheckOut){cell.classList.add("range");}grid.appendChild(cell);}}
function previousMonth(){currentMonth--;if(currentMonth<0){currentMonth=11;currentYear--;}renderCalendar();}function nextMonth(){currentMonth++;if(currentMonth>11){currentMonth=0;currentYear++;}renderCalendar();}
async function submitBooking(event){event.preventDefault();try{const formData=new FormData(document.getElementById("guestBookingForm")),bookingPayload={firstName:formData.get("firstName"),lastName:formData.get("lastName"),email:formData.get("email"),mobile:formData.get("mobile"),address:formData.get("address"),room:document.getElementById("room").value||null,parking:document.getElementById("parking").value||null,parkingOnly:document.getElementById("bookingType").value==="parking",checkIn:document.getElementById("checkIn").value,checkOut:document.getElementById("checkOut").value,adults:Number(document.getElementById("guests").value||2),children:Number(document.getElementById("children").value||0),totalAmount:document.getElementById("totalAmount").textContent.replace(/[^0-9.]/g,"")};if(!bookingPayload.firstName||!bookingPayload.lastName||!bookingPayload.email||!bookingPayload.mobile||!bookingPayload.address){alert("Please fill in all required fields.");return;}if(!bookingPayload.checkIn||!bookingPayload.checkOut){alert("Please select check-in and check-out dates.");return;}if(!bookingPayload.room&&!bookingPayload.parking){alert("Please select accommodation or parking.");return;}const bookingResponse=await fetch(`${API}/bookings`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(bookingPayload)});if(!bookingResponse.ok){const error=await bookingResponse.json();alert(`Booking failed: ${error.message||"Unknown error"}`);return;}const booking=await bookingResponse.json();if(booking.data){localStorage.setItem("guestBooking",JSON.stringify(booking.data));window.location.href="/guest-booking/payment.html";}else{alert("Booking created but no confirmation data received.");}}catch(err){console.error("Booking submission error:",err);alert(`Error submitting booking: ${err.message}`);}}

const prevBtn=document.getElementById("prevMonth");const nextBtn=document.getElementById("nextMonth");if(prevBtn)prevBtn.addEventListener("click",previousMonth);if(nextBtn)nextBtn.addEventListener("click",nextMonth);