const UNIT_GALLERY_API="https://ca-smart-staycation-muqd.onrender.com/api";
(function(){
  const css=`.unit-info-panel{margin-top:14px;padding:16px;border:1px solid #e2ddd5;border-radius:10px;background:#fff}.unit-info-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(220px,340px);gap:20px;align-items:start}.unit-details{min-width:0}.unit-gallery{min-width:0}.unit-primary-photo{width:100%;height:230px;object-fit:cover;border-radius:8px;cursor:pointer;border:1px solid #ddd;display:block}.unit-photo-thumbs{display:flex;gap:7px;overflow-x:auto;margin-top:8px}.unit-photo-thumbs img{width:58px;height:48px;object-fit:cover;border-radius:5px;border:1px solid #ddd;cursor:pointer;flex:none}.unit-info-panel h4{margin:0 0 5px;font-size:20px}.unit-info-panel .unit-category{color:#777;margin-bottom:10px}.unit-info-panel .unit-description{line-height:1.55;margin:0 0 12px}.unit-info-panel .unit-meta{display:grid;grid-template-columns:1fr 1fr;gap:7px;font-size:13px}.unit-info-panel .unit-meta div{padding:8px;background:#f8f6f2;border-radius:6px}.unit-amenities{margin-top:12px}.unit-amenities span{display:inline-block;margin:4px 5px 0 0;padding:5px 8px;border:1px solid #ddd;border-radius:15px;font-size:12px}.unit-lightbox{position:fixed;inset:0;background:#000d;z-index:9999;display:flex;align-items:center;justify-content:center;padding:25px}.unit-lightbox img{max-width:94vw;max-height:88vh;object-fit:contain;border-radius:8px}.unit-lightbox button{position:absolute;right:22px;top:14px;background:none;border:0;color:#fff;font-size:42px;cursor:pointer}@media(max-width:700px){.unit-info-layout{grid-template-columns:1fr}.unit-primary-photo{height:210px}.unit-info-panel .unit-meta{grid-template-columns:1fr}}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  let units=[];
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function openPhoto(url){const m=document.createElement('div');m.className='unit-lightbox';m.innerHTML=`<button type="button" aria-label="Close">×</button><img src="${esc(url)}" alt="Accommodation photo">`;m.querySelector('button').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};document.body.appendChild(m)}
  function selected(){const id=document.getElementById('room')?.value;return units.find(x=>String(x._id)===String(id))||null}
  function render(){
    const room=document.getElementById('room'),group=document.getElementById('roomGroup');if(!room||!group)return;
    let panel=document.getElementById('unitInfoPanel');if(!panel){panel=document.createElement('div');panel.id='unitInfoPanel';panel.className='unit-info-panel';group.appendChild(panel)}
    const u=selected();if(!u){panel.innerHTML='<p style="margin:0;color:#888">Select an accommodation to view room information and photos.</p>';return}
    const images=Array.isArray(u.images)?u.images.filter(Boolean):[];const primary=images[0];
    panel.innerHTML=`<div class="unit-info-layout"><div class="unit-details"><h4>${esc(u.unitName||u.unitNumber||'Accommodation')}</h4><div class="unit-category">${esc(u.category||'Accommodation')}</div><p class="unit-description">${esc(u.description||'Room information will be shown here.')}</p><div class="unit-meta"><div><strong>Capacity</strong><br>${esc(u.capacity||0)} guest(s)</div><div><strong>Nightly Rate</strong><br>₱${Number(u.price||0).toLocaleString()}</div>${Number(u.weekendPrice||0)?`<div><strong>Weekend Rate</strong><br>₱${Number(u.weekendPrice).toLocaleString()}</div>`:''}${Number(u.holidayPrice||0)?`<div><strong>Holiday Rate</strong><br>₱${Number(u.holidayPrice).toLocaleString()}</div>`:''}<div><strong>Status</strong><br>${esc(u.status||'Available')}</div></div>${(u.amenities||[]).length?`<div class="unit-amenities"><strong>Amenities</strong><br>${u.amenities.map(a=>`<span>${esc(a)}</span>`).join('')}</div>`:''}</div><div class="unit-gallery">${primary?`<img class="unit-primary-photo" src="${esc(primary)}" alt="${esc(u.unitName||'Accommodation')}" data-photo="0"><div class="unit-photo-thumbs">${images.map((img,i)=>`<img src="${esc(img)}" alt="Photo ${i+1}" data-photo="${i}">`).join('')}</div>`:'<div style="display:flex;align-items:center;justify-content:center;min-height:230px;background:#f5f3ef;border-radius:8px;color:#888">No photos available</div>'}</div></div>`;
    panel.querySelectorAll('[data-photo]').forEach(el=>el.addEventListener('click',()=>openPhoto(images[Number(el.dataset.photo)])));
  }
  async function load(){try{const r=await fetch(`${UNIT_GALLERY_API}/rooms`,{cache:'no-store'}),j=await r.json();if(r.ok&&Array.isArray(j.data)){units=j.data;render()}}catch(e){console.warn('Unable to load accommodation details',e)}}
  document.addEventListener('DOMContentLoaded',()=>{const room=document.getElementById('room');if(room)room.addEventListener('change',render);load()});
})();
