/* Admin review UI for additional guest / amenity requests. */
(function(){
  const API="https://ca-smart-staycation-muqd.onrender.com/api", tokenKey="caSmartAdminToken";
  const token=()=>sessionStorage.getItem(tokenKey)||"";
  const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const money=v=>`₱${Number(v||0).toLocaleString('en-PH')}`;
  function styles(){if(document.getElementById('adminAddonStyles'))return;const s=document.createElement('style');s.id='adminAddonStyles';s.textContent='.admin-addon-panel{margin:18px 0;padding:18px;border:1px solid #e2e8e5;border-radius:10px;background:#fff}.admin-addon-panel h3{margin:0;color:#173f35}.admin-addon-sub{margin:5px 0 14px;color:#68736e;font-size:13px}.admin-addon-card{border:1px solid #e1e6e3;border-radius:8px;padding:13px;margin:10px 0;background:#fafcfb}.admin-addon-card strong{color:#173f35}.admin-addon-meta{font-size:12px;color:#68736e;line-height:1.6;margin:6px 0}.admin-addon-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.admin-addon-actions button{width:auto;margin:0;padding:8px 12px}.admin-addon-view{display:inline-block;padding:8px 12px;border-radius:7px;background:#eef3f0;color:#173f35;text-decoration:none;font-weight:700;font-size:13px}.admin-addon-approve{background:#173f35!important}.admin-addon-reject{background:#b42318!important}.admin-addon-empty{color:#68736e;font-size:13px;padding:8px 0}@media(max-width:600px){.admin-addon-actions{flex-direction:column;align-items:stretch}.admin-addon-actions button,.admin-addon-view{width:100%;box-sizing:border-box;text-align:center}}';document.head.appendChild(s)}
  async function load(){if(!token())return;styles();let panel=document.getElementById('adminAddonPanel');if(!panel){panel=document.createElement('section');panel.id='adminAddonPanel';panel.className='admin-addon-panel';const alert=document.getElementById('paymentAlert');const stats=document.querySelector('.stats');(alert?.parentNode||stats?.parentNode)?.insertBefore(panel,stats||null)}try{const r=await fetch(`${API}/admin/add-on-requests`,{headers:{Authorization:`Bearer ${token()}`},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.message||'Unable to load requests.');const rows=d.data||[];panel.innerHTML=`<h3>Additional Guest & Amenity Requests</h3><div class="admin-addon-sub">Guests must upload payment proof immediately. Review and verify each payment before approving the request.</div>${rows.length?rows.map(render).join(''):'<div class="admin-addon-empty">No additional guest or amenity requests are waiting for payment verification.</div>'}`;}catch(e){panel.innerHTML=`<h3>Additional Guest & Amenity Requests</h3><div class="admin-addon-empty">Unable to load requests. Please refresh the page.</div>`;console.warn('ADMIN ADD-ON LOAD:',e.message)}}
  function render(r){const proof=r.paymentProof?`${API}/uploads/payments/${encodeURIComponent(r.paymentProof)}`:'';return `<div class="admin-addon-card"><strong>${esc(r.bookingReference||'Booking')}</strong> — ${esc(r.guestName||'Guest')}<div class="admin-addon-meta">${Number(r.extraGuests||0)} additional guest(s) · ${Number(r.amenitySets||0)} complete towel/toiletries/bedsheet/blanket set(s) · <strong>${money(r.amount)}</strong><br>Payment submitted: ${r.paymentSubmittedAt?new Date(r.paymentSubmittedAt).toLocaleString('en-PH'): '—'}</div><div class="admin-addon-actions">${proof?`<a class="admin-addon-view" href="${proof}" target="_blank" rel="noopener">View Payment Proof</a>`:''}<button class="admin-addon-approve" onclick="window.verifyGuestAddon('${esc(r.bookingId)}','${esc(r._id)}','approve')">Approve Payment</button><button class="admin-addon-reject" onclick="window.verifyGuestAddon('${esc(r.bookingId)}','${esc(r._id)}','reject')">Reject Payment</button></div></div>`}
  window.verifyGuestAddon=async function(bookingId,requestId,action){let note='';if(action==='reject'){note=prompt('Reason for rejecting this add-on payment proof:')||'';if(!note)return;}if(!confirm(action==='approve'?'Approve this payment and add the requested charge/guest to the booking?':'Reject this add-on payment proof?'))return;try{const r=await fetch(`${API}/admin/bookings/${encodeURIComponent(bookingId)}/add-ons/${encodeURIComponent(requestId)}/verify`,{method:'PUT',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({action,note})}),d=await r.json();if(!r.ok)throw Error(d.message||'Unable to process request.');alert(d.message);if(typeof window.loadBookings==='function')await window.loadBookings(true);load();}catch(e){alert(e.message)}};
  function boot(){load();setInterval(load,15000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
