const ADMIN_BOOKING_API = "https://ca-smart-staycation-muqd.onrender.com/api";
const AB_ROOM_RATE_FALLBACK = 2800;
const AB_EXTRA_GUEST_FEE = 300;
const AB_PARKING_RATE_FIXED = 500;
const AB_SECURITY_DEPOSIT = 1000;
let adminRooms = [];
let adminParking = [];
const ab = id => document.getElementById(id);
const abMoney = value => `₱${Number(value || 0).toLocaleString("en-PH")}`;
function adminToken(){return sessionStorage.getItem("caSmartAdminToken")||"";}
function adminHeaders(){return {"Content-Type":"application/json",Authorization:`Bearer ${adminToken()}`};}
function localDateString(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function nights(){const a=ab("abCheckIn").value,b=ab("abCheckOut").value;if(!a||!b)return 0;return Math.max(0,(new Date(`${b}T00:00:00`)-new Date(`${a}T00:00:00`))/86400000);}
function selectedRoom(){return adminRooms.find(r=>String(r._id)===ab("abRoom").value)||adminRooms[0]||null;}
function selectedParking(){return adminParking.find(p=>String(p._id)===ab("abParking").value)||null;}
function adminBookingTotal(){const n=nights(),adults=Math.max(1,Number(ab("abAdults").value||1)),po=ab("abParkingOnly").value==="true",room=selectedRoom(),parking=selectedParking(),extra=Math.max(0,adults-2),roomCharge=po?0:Number(room?.price||AB_ROOM_RATE_FALLBACK)*n,extraCharge=po?0:extra*AB_EXTRA_GUEST_FEE*n,parkingCharge=parking?n*AB_PARKING_RATE_FIXED:0,total=roomCharge+extraCharge+parkingCharge+AB_SECURITY_DEPOSIT;return{n,roomCharge,extraCharge,parkingCharge,total,extra,parkingRate:AB_PARKING_RATE_FIXED};}
function updateAdminBookingSummary(){const x=adminBookingTotal();ab("abSummary").innerHTML=`<div><span>Nights</span><strong>${x.n}</strong></div><div><span>Accommodation</span><strong>${abMoney(x.roomCharge)}</strong></div>${x.extraCharge?`<div><span>Extra guests</span><strong>${abMoney(x.extraCharge)}</strong></div>`:""}${x.parkingCharge?`<div><span>Parking</span><strong>${abMoney(x.parkingCharge)}</strong></div>`:""}<div><span>Refundable security deposit</span><strong>${abMoney(AB_SECURITY_DEPOSIT)}</strong></div><div class="grand"><span>TOTAL AMOUNT</span><strong>${abMoney(x.total)}</strong></div>`;}
function updateDocumentRequirements(){const po=ab("abParkingOnly").value==="true",hasParking=po||!!ab("abParking").value,gov=ab("abGovernmentId"),license=ab("abDriversLicense");ab("abGovIdWrap").style.display=po?"none":"";gov.required=!po;["abLicenseWrap","abVehicleBrandWrap","abVehicleModelWrap","abVehicleColorWrap","abPlateWrap"].forEach(id=>ab(id).style.display=hasParking?"":"none");license.required=hasParking;["abVehicleBrand","abVehicleModel","abVehicleColor","abPlateNumber"].forEach(id=>ab(id).required=hasParking);}
async function loadAdminBookingOptions(){if(!adminToken())return;try{const [rr,pr]=await Promise.all([fetch(`${ADMIN_BOOKING_API}/rooms`,{cache:"no-store"}),fetch(`${ADMIN_BOOKING_API}/parking`,{cache:"no-store"})]);const rj=await rr.json(),pj=await pr.json();adminRooms=Array.isArray(rj.data)?rj.data:[];adminParking=Array.isArray(pj.data)?pj.data:[];const availableRooms=adminRooms.filter(r=>r.status!=="Maintenance");ab("abRoom").innerHTML=availableRooms.map(r=>`<option value="${r._id}">${r.unitNumber} — ${r.unitName} (${abMoney(r.price||AB_ROOM_RATE_FALLBACK)}/night)</option>`).join("")||`<option value="">No accommodation available</option>`;ab("abParking").innerHTML=`<option value="">No parking</option>`+adminParking.filter(p=>p.status!=="Maintenance").map(p=>`<option value="${p._id}">${p.parkingNumber||p.parkingName||"Parking"} (₱500/night)</option>`).join("");
// Guest-booking behavior: guest count and parking are selectable.
ab("abAdults").disabled=false;ab("abAdults").readOnly=false;ab("abParking").disabled=false;ab("abParking").removeAttribute("readonly");
updateDocumentRequirements();updateAdminBookingSummary();}catch(e){console.error(e);ab("abError").textContent="Unable to load accommodations or parking options.";}}
function openAdminBooking(){ab("adminBookingModal").hidden=false;ab("abError").textContent="";const t=localDateString();ab("abCheckIn").min=t;ab("abCheckOut").min=t;ab("abAdults").disabled=false;ab("abAdults").readOnly=false;ab("abParking").disabled=false;ab("abParking").removeAttribute("readonly");loadAdminBookingOptions();updateDocumentRequirements();updateAdminBookingSummary();}
function closeAdminBooking(){ab("adminBookingModal").hidden=true;}
function validateFile(file,label){if(!file)return null;if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new Error(`${label} must be JPG, PNG, WEBP, or PDF.`);if(file.size>10*1024*1024)throw new Error(`${label} must be smaller than 10 MB.`);return file;}
async function uploadAdminDocuments(id){const po=ab("abParkingOnly").value==="true",g=ab("abGovernmentId").files?.[0]||null,l=ab("abDriversLicense").files?.[0]||null,hp=po||!!ab("abParking").value;if(!po&&!g)throw new Error("Please upload a clear government-issued ID.");if(hp&&!l)throw new Error("Please upload the driver's license required for parking.");validateFile(g,"Government ID");validateFile(l,"Driver's License");const fd=new FormData();if(g)fd.append("governmentId",g);if(l)fd.append("driversLicense",l);fd.append("vehicleBrand",ab("abVehicleBrand").value.trim());fd.append("vehicleModel",ab("abVehicleModel").value.trim());fd.append("vehicleColor",ab("abVehicleColor").value.trim());fd.append("plateNumber",ab("abPlateNumber").value.trim());const r=await fetch(`${ADMIN_BOOKING_API}/bookings/${encodeURIComponent(id)}/documents`,{method:"POST",body:fd}),j=await r.json();if(!r.ok)throw new Error(j.message||"Guest document upload failed.");return j;}
async function submitAdminBooking(e){e.preventDefault();const x=adminBookingTotal(),room=selectedRoom(),parking=selectedParking(),po=ab("abParkingOnly").value==="true",ci=ab("abCheckIn").value,co=ab("abCheckOut").value,adults=Number(ab("abAdults").value||0),hp=po||!!parking;if(!adminToken())return void(ab("abError").textContent="Your admin session has expired. Please sign in again.");if(!x.n)return void(ab("abError").textContent="Please select a valid check-in and check-out date.");if(!po&&!room)return void(ab("abError").textContent="No accommodation is available.");if(adults<1||adults>4)return void(ab("abError").textContent="Number of guests must be between 1 and 4 adults.");if(!po&&!ab("abGovernmentId").files?.[0])return void(ab("abError").textContent="Government-issued ID is required.");if(hp){if(!ab("abDriversLicense").files?.[0])return void(ab("abError").textContent="Driver's License is required for parking.");for(const id of ["abVehicleBrand","abVehicleModel","abVehicleColor","abPlateNumber"])if(!ab(id).value.trim())return void(ab("abError").textContent="Complete all vehicle information required for parking.");}const btn=e.submitter;btn.disabled=true;btn.textContent="Creating…";try{const body={firstName:ab("abFirstName").value.trim(),lastName:ab("abLastName").value.trim(),email:ab("abEmail").value.trim(),mobile:ab("abMobile").value.trim(),address:ab("abAddress").value.trim(),room:po?null:room._id,parking:parking?parking._id:null,parkingOnly:po,checkIn:ci,checkOut:co,adults,children:Math.max(0,Number(ab("abChildren").value||0)),totalAmount:x.total,paymentStatus:ab("abPaymentStatus").value,paymentReference:ab("abPaymentReference").value.trim(),notes:ab("abNotes").value.trim(),vehicleBrand:ab("abVehicleBrand").value.trim(),vehicleModel:ab("abVehicleModel").value.trim(),vehicleColor:ab("abVehicleColor").value.trim(),plateNumber:ab("abPlateNumber").value.trim()};const r=await fetch(`${ADMIN_BOOKING_API}/admin/bookings`,{method:"POST",headers:adminHeaders(),body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.message||"Unable to create booking.");await uploadAdminDocuments(j.data._id);alert(`Booking created successfully.\nReference: ${j.data?.bookingReference||"—"}`);closeAdminBooking();if(typeof loadBookings==="function")await loadBookings();ab("adminBookingForm").reset();ab("abAdults").disabled=false;ab("abAdults").readOnly=false;ab("abParking").disabled=false;updateDocumentRequirements();updateAdminBookingSummary();}catch(err){console.error(err);ab("abError").textContent=err.message||"Unable to create booking.";}finally{btn.disabled=false;btn.textContent="Create Booking";}}
ab("navNewBooking").addEventListener("click",openAdminBooking);ab("adminBookingClose").addEventListener("click",closeAdminBooking);ab("adminBookingCancel").addEventListener("click",closeAdminBooking);ab("adminBookingForm").addEventListener("submit",submitAdminBooking);ab("abParkingOnly").addEventListener("change",updateDocumentRequirements);ab("abParking").addEventListener("change",updateDocumentRequirements);["abCheckIn","abCheckOut","abAdults","abChildren","abParking"].forEach(id=>ab(id).addEventListener("input",updateAdminBookingSummary));ab("abCheckIn").addEventListener("change",()=>{const v=ab("abCheckIn").value;ab("abCheckOut").min=v||localDateString();if(ab("abCheckOut").value&&v&&ab("abCheckOut").value<=v)ab("abCheckOut").value="";updateAdminBookingSummary();});ab("adminBookingModal").addEventListener("click",e=>{if(e.target.id==="adminBookingModal")closeAdminBooking();});