const API="https://ca-smart-staycation-muqd.onrender.com/api";
let rooms=[],parking=[],editing=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function get(path){const r=await fetch(API+path);const j=await r.json();if(!r.ok)throw Error(j.message||"Request failed");return j.data||[]}
async function send(path,method,body){const r=await fetch(API+path,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.message||"Request failed");return j.data}
function render(){
 $("rooms").innerHTML=rooms.length?rooms.map(r=>`<div class="resource"><div><div class="name">${esc(r.unitNumber||"Unit")}</div><div class="meta">${esc(r.unitName||"")} · ${esc(r.category||"")} · ₱${Number(r.price||0).toLocaleString()}/night · capacity ${esc(r.capacity||0)}</div><span class="badge ${String(r.status).toLowerCase()==="available"?"available":"occupied"}">${esc(r.status||"Unknown")}</span></div><div class="actions"><button onclick="editRoom('${r._id}')">Edit</button><button class="danger" onclick="removeResource('room','${r._id}')">Delete</button></div></div>`).join(""):"<div class='muted'>No accommodation records.</div>";
 $("parking").innerHTML=parking.length?parking.map(p=>`<div class="resource"><div><div class="name">${esc(p.parkingNumber||"Parking")}</div><div class="meta">${esc(p.parkingName||"")} · ₱${Number(p.rate||0).toLocaleString()}/night</div><span class="badge ${String(p.status).toLowerCase()==="available"?"available":"occupied"}">${esc(p.status||"Unknown")}</span></div><div class="actions"><button onclick="editParking('${p._id}')">Edit</button><button class="danger" onclick="removeResource('parking','${p._id}')">Delete</button></div></div>`).join(""):"<div class='muted'>No parking records.</div>";
}
function openForm(type,item=null){editing={type,id:item?item._id:null};$("modalTitle").textContent=item?`Edit ${type==='room'?'Unit':'Parking Slot'}`:`Add ${type==='room'?'Unit':'Parking Slot'}`;const room=type==='room';$("resourceForm").innerHTML=room?`<div class="field"><label>Unit Number</label><input name="unitNumber" value="${esc(item?.unitNumber)}" required></div><div class="field"><label>Unit Name</label><input name="unitName" value="${esc(item?.unitName)}" required></div><div class="field"><label>Category</label><input name="category" value="${esc(item?.category||'Studio')}"></div><div class="field"><label>Nightly Rate</label><input type="number" name="price" min="0" value="${item?.price??2800}" required></div><div class="field"><label>Capacity</label><input type="number" name="capacity" min="1" value="${item?.capacity??2}" required></div><div class="field"><label>Status</label><select name="status"><option ${item?.status==='Available'?'selected':''}>Available</option><option ${item?.status==='Occupied'?'selected':''}>Occupied</option><option ${item?.status==='Maintenance'?'selected':''}>Maintenance</option></select></div>`:`<div class="field"><label>Parking Number</label><input name="parkingNumber" value="${esc(item?.parkingNumber)}" required></div><div class="field"><label>Parking Name</label><input name="parkingName" value="${esc(item?.parkingName)}"></div><div class="field"><label>Rate per Night</label><input type="number" name="rate" min="0" value="${item?.rate??500}" required></div><div class="field"><label>Status</label><select name="status"><option ${item?.status==='Available'?'selected':''}>Available</option><option ${item?.status==='Occupied'?'selected':''}>Occupied</option><option ${item?.status==='Maintenance'?'selected':''}>Maintenance</option></select></div>`+`<div class="form-actions"><button type="button" onclick="closeModal()">Cancel</button><button class="save" type="submit">Save</button></div>`;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden");editing=null}
async function save(e){e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f.entries());if(editing.type==='room'){body.price=Number(body.price);body.capacity=Number(body.capacity)}else body.rate=Number(body.rate);try{await send(editing.type==='room'?`/rooms${editing.id?'/'+editing.id:''}`:`/parking${editing.id?'/'+editing.id:''}`,editing.id?'PUT':'POST',body);closeModal();await load()}catch(err){alert(err.message)}}
async function removeResource(type,id){if(!confirm(`Delete this ${type==='room'?'unit':'parking slot'}?`))return;try{await send(type==='room'?`/rooms/${id}`:`/parking/${id}`,'DELETE',{});await load()}catch(err){alert(err.message)}}
function editRoom(id){openForm('room',rooms.find(x=>x._id===id))}function editParking(id){openForm('parking',parking.find(x=>x._id===id))}
async function load(){try{[rooms,parking]=await Promise.all([get('/rooms'),get('/parking')]);render()}catch(e){console.error(e);alert('Unable to load units and parking. Check the API connection.')}}
$("addRoomBtn").onclick=()=>openForm('room');$("addParkingBtn").onclick=()=>openForm('parking');$("closeModal").onclick=closeModal;$("resourceForm").onsubmit=save;$("refreshBtn").onclick=load;load();
