const API="https://ca-smart-staycation-muqd.onrender.com/api";
let rooms=[],parking=[],editing=null,selectedImages=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const token=()=>sessionStorage.getItem("caSmartAdminToken")||"";
const headers=()=>({"Content-Type":"application/json",Authorization:`Bearer ${token()}`});
function ensureAdmin(){if(!token()){alert("Please sign in to the admin account first.");window.location.href="bookings.html";return false}return true}
async function get(path){const r=await fetch(API+path,{cache:"no-store"}),j=await r.json();if(!r.ok)throw Error(j.message||"Request failed");return j.data||[]}
async function send(path,method,body){const r=await fetch(API+path,{method,headers:headers(),body:JSON.stringify(body)}),j=await r.json();if(r.status===401||r.status===403){sessionStorage.removeItem("caSmartAdminToken");throw Error("Your admin session has expired. Please sign in again.")}if(!r.ok)throw Error(j.message||"Request failed");return j.data}
function statusClass(s){return String(s||"").toLowerCase()==="available"?"available":"occupied"}
function render(){
$("rooms").innerHTML=rooms.length?rooms.map(r=>`<div class="resource"><div class="resource-main">${(r.images||[]).length?`<div class="unit-thumb-strip">${(r.images||[]).slice(0,4).map((src,i)=>`<img src="${esc(src)}" alt="${esc(r.unitName||'Unit')} photo ${i+1}" onclick="viewImage('${esc(src)}')">`).join("")}</div>`:""}<div><div class="name">${esc(r.unitNumber||"Unit")} — ${esc(r.unitName||"")}</div><div class="meta">${esc(r.category||"")} · ₱${Number(r.price||0).toLocaleString()}/night · weekend ₱${Number(r.weekendPrice||0).toLocaleString()} · holiday ₱${Number(r.holidayPrice||0).toLocaleString()} · capacity ${esc(r.capacity||0)}</div><span class="badge ${statusClass(r.status)}">${esc(r.status||"Unknown")}</span></div></div><div class="actions"><button onclick="editRoom('${r._id}')">Edit</button><button class="danger" onclick="removeResource('room','${r._id}')">Delete</button></div></div>`).join(""):"<div class='muted'>No accommodation records.</div>";
$("parking").innerHTML=parking.length?parking.map(p=>`<div class="resource"><div><div class="name">${esc(p.parkingNumber||"Parking")} — ${esc(p.parkingName||"")}</div><div class="meta">₱${Number(p.rate||0).toLocaleString()}/night</div><span class="badge ${statusClass(p.status)}">${esc(p.status||"Unknown")}</span></div><div class="actions"><button onclick="editParking('${p._id}')">Edit</button><button class="danger" onclick="removeResource('parking','${p._id}')">Delete</button></div></div>`).join(""):"<div class='muted'>No parking records.</div>";
}
function openForm(type,item=null){
 editing={type,id:item?item._id:null};selectedImages=[...(item?.images||[])];const room=type==='room';
 $("modalTitle").textContent=item?`Edit ${room?'Unit':'Parking Slot'}`:`Add ${room?'Unit':'Parking Slot'}`;
 const formFields=room?`<div class="field"><label>Unit Number</label><input name="unitNumber" value="${esc(item?.unitNumber)}" placeholder="e.g. UNIT 1" required></div><div class="field"><label>Unit Name</label><input name="unitName" value="${esc(item?.unitName)}" placeholder="e.g. Studio Unit" required></div><div class="field"><label>Category</label><input name="category" value="${esc(item?.category||'Studio')}" placeholder="Studio / 1 Bedroom / 2 Bedroom"></div><div class="field"><label>Nightly Price</label><input type="number" name="price" min="0" step="0.01" value="${item?.price??2800}" required></div><div class="field"><label>Weekend Price</label><input type="number" name="weekendPrice" min="0" step="0.01" value="${item?.weekendPrice??0}"></div><div class="field"><label>Holiday Price</label><input type="number" name="holidayPrice" min="0" step="0.01" value="${item?.holidayPrice??0}"></div><div class="field"><label>Capacity</label><input type="number" name="capacity" min="1" value="${item?.capacity??2}" required></div><div class="field"><label>Status</label><select name="status"><option ${item?.status==='Available'?'selected':''}>Available</option><option ${item?.status==='Reserved'?'selected':''}>Reserved</option><option ${item?.status==='Occupied'?'selected':''}>Occupied</option><option ${item?.status==='Maintenance'?'selected':''}>Maintenance</option></select></div><div class="field full"><label>Amenities</label><input name="amenities" value="${esc((item?.amenities||[]).join(', '))}" placeholder="Wi-Fi, TV, Kitchen, Air Conditioning"></div><div class="field full"><label>Description</label><textarea name="description" placeholder="Unit description">${esc(item?.description||'')}</textarea></div><div class="field full"><label>Accommodation Photos</label><input id="unitImages" type="file" accept="image/*" multiple><small class="upload-help">Upload up to 8 photos. Existing photos can be removed below.</small><div id="imagePreview" class="admin-image-preview"></div></div>`:`<div class="field"><label>Parking Number</label><input name="parkingNumber" value="${esc(item?.parkingNumber)}" placeholder="e.g. SLOT 1" required></div><div class="field"><label>Parking Name</label><input name="parkingName" value="${esc(item?.parkingName)}" placeholder="e.g. Basement Parking"></div><div class="field"><label>Rate per Night</label><input type="number" name="rate" min="0" step="0.01" value="${item?.rate??500}" required></div><div class="field"><label>Status</label><select name="status"><option ${item?.status==='Available'?'selected':''}>Available</option><option ${item?.status==='Occupied'?'selected':''}>Occupied</option><option ${item?.status==='Maintenance'?'selected':''}>Maintenance</option></select></div>`;
 $("resourceForm").innerHTML=formFields;
 $("modal").classList.remove("hidden");if(room){renderImagePreview();$("unitImages").onchange=handleImages}}
function renderImagePreview(){const p=$("imagePreview");if(!p)return;p.innerHTML=selectedImages.length?selectedImages.map((src,i)=>`<div class="admin-image-item"><img src="${esc(src)}" onclick="viewImage('${esc(src)}')"><button type="button" onclick="removeImage(${i})">Remove</button><small>Photo ${i+1}</small></div>`).join(""):"<small class='muted'>No photos selected.</small>"}
function viewImage(src){const d=document.createElement("div");d.className="image-lightbox";d.innerHTML=`<button type="button">×</button><img src="${esc(src)}">`;d.onclick=e=>{if(e.target===d||e.target.tagName==='BUTTON')d.remove()};document.body.appendChild(d)}
function removeImage(i){selectedImages.splice(i,1);renderImagePreview()}
function compressImage(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(Error('Only image files are allowed.'));const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=()=>reject(Error('Unable to read image.'));img.src=reader.result};reader.onerror=()=>reject(Error('Unable to read image.'));reader.readAsDataURL(file)})}
async function handleImages(e){try{const files=[...e.target.files];if(selectedImages.length+files.length>8){alert('You can upload up to 8 accommodation photos.');e.target.value='';return}const added=await Promise.all(files.map(compressImage));selectedImages.push(...added);renderImagePreview();e.target.value=''}catch(err){alert(err.message)}}
function closeModal(){$("modal").classList.add("hidden");editing=null;selectedImages=[]}
async function save(e){if(e&&e.preventDefault)e.preventDefault();const f=new FormData($("resourceForm")),body=Object.fromEntries(f.entries());if(editing.type==='room'){body.price=Number(body.price);body.weekendPrice=Number(body.weekendPrice||0);body.holidayPrice=Number(body.holidayPrice||0);body.capacity=Number(body.capacity);body.amenities=String(body.amenities||'').split(',').map(x=>x.trim()).filter(Boolean);body.images=selectedImages}else body.rate=Number(body.rate);try{await send(editing.type==='room'?`/rooms${editing.id?'/'+editing.id:''}`:`/parking${editing.id?'/'+editing.id:''}`,editing.id?'PUT':'POST',body);closeModal();await load()}catch(err){alert(err.message)}}
async function removeResource(type,id){if(!ensureAdmin())return;if(!confirm(`Delete this ${type==='room'?'unit':'parking slot'}? This cannot be undone.`))return;try{await send(type==='room'?`/rooms/${id}`:`/parking/${id}`,'DELETE',{});await load()}catch(err){alert(err.message)}}
function editRoom(id){openForm('room',rooms.find(x=>x._id===id))}function editParking(id){openForm('parking',parking.find(x=>x._id===id))}
async function load(){if(!ensureAdmin())return;try{[rooms,parking]=await Promise.all([get('/rooms'),get('/parking')]);render()}catch(e){console.error(e);alert(e.message||'Unable to load units and parking.');if(String(e.message||'').toLowerCase().includes('session'))window.location.href='bookings.html'}}
$("addRoomBtn").onclick=()=>{if(ensureAdmin())openForm('room')};$("addParkingBtn").onclick=()=>{if(ensureAdmin())openForm('parking')};$("closeModal").onclick=closeModal;$("cancelResource").onclick=closeModal;$("saveResource").onclick=()=>save();$("resourceForm").onsubmit=save;$("refreshBtn").onclick=load;load();