(() => {
  const API = "https://ca-smart-staycation-muqd.onrender.com/api";
  const token = () => sessionStorage.getItem("caSmartAdminToken") || "";
  const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${token()}` });
  function addTab(){const nav=document.querySelector(".admin-nav");if(!nav||document.getElementById("voucherManagementTab"))return;const resources=Array.from(nav.querySelectorAll("a")).find(a=>/Units & Parking Management/i.test(a.textContent));const tab=document.createElement("a");tab.id="voucherManagementTab";tab.href="#voucherManagement";tab.textContent="Voucher Management";tab.className="voucher-management-tab";if(resources)resources.insertAdjacentElement("afterend",tab);else nav.appendChild(tab);tab.addEventListener("click",e=>{e.preventDefault();showTab(true)})}
  function addStyles(){if(document.getElementById("voucherTabStyles"))return;const s=document.createElement("style");s.id="voucherTabStyles";s.textContent=`.voucher-management-tab{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 14px;border-radius:7px;background:#eef3f0;color:#173f35;border:1px solid #d7e1dc;text-decoration:none;font-weight:700}.voucher-management-tab.active{background:#173f35;color:#fff;border-color:#173f35}#voucherAdminCard.voucher-tab-panel{display:none!important;margin-top:18px}#voucherAdminCard.voucher-tab-panel.active{display:block!important}.voucher-delete-btn{background:#fff!important;color:#a1261f!important;border:1px solid #d9b1ad!important}.voucher-delete-btn:hover{background:#fff4f3!important}`;document.head.appendChild(s)}
  function getCard(){return document.getElementById("voucherAdminCard")}
  function showTab(active){const card=getCard(),tab=document.getElementById("voucherManagementTab");if(!card||!tab)return;card.classList.add("voucher-tab-panel");card.classList.toggle("active",!!active);tab.classList.toggle("active",!!active);if(active){card.scrollIntoView({behavior:"smooth",block:"start"});setTimeout(addDeleteButtons,100);setTimeout(replaceCertificateButtons,120)}}
  function hideTab(){const card=getCard(),tab=document.getElementById("voucherManagementTab");if(card){card.classList.add("voucher-tab-panel");card.classList.remove("active")}if(tab)tab.classList.remove("active")}
  async function deleteVoucher(id,code){if(!confirm(`Delete voucher ${code}? This cannot be undone.`))return;try{const r=await fetch(`${API}/vouchers/${id}`,{method:"DELETE",headers:headers()}),j=await r.json();if(!r.ok)throw new Error(j.message||"Unable to delete voucher.");const refresh=window.loadAdminVouchers;if(typeof refresh==="function")await refresh();setTimeout(addDeleteButtons,100);setTimeout(replaceCertificateButtons,120)}catch(e){alert(e.message||"Unable to delete voucher.")}}
  function addDeleteButtons(){const list=document.getElementById("voucherAdminList");if(!list)return;list.querySelectorAll(".voucher-admin-item").forEach(row=>{if(row.querySelector(".voucher-delete-btn"))return;const buttons=row.querySelectorAll("button[data-voucher-id]"),id=buttons[0]?.dataset.voucherId;if(!id)return;row.dataset.voucherId=id;const code=row.querySelector("strong")?.textContent?.trim()||"this voucher",actions=row.querySelector(".voucher-admin-actions");if(!actions)return;const btn=document.createElement("button");btn.type="button";btn.className="voucher-delete-btn";btn.textContent="Delete";btn.addEventListener("click",()=>deleteVoucher(id,code));actions.appendChild(btn)})}
  function loadQr(text){return new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin="anonymous";img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Unable to load QR code."));img.src=`https://api.qrserver.com/v1/create-qr-code/?size=300x300&margin=8&data=${encodeURIComponent(text)}`})}
  async function drawLuxuryCertificate(v,guest){const qr=await loadQr("https://casmartstaycation.github.io/cassbooking/"),c=document.createElement("canvas"),x=c.getContext("2d"),W=1800,H=1000;c.width=W;c.height=H;
    x.fillStyle="#fbf7ee";x.fillRect(0,0,W,H);
    // NEW BORDER: clean French Art-Deco hotel frame, replacing the previous heavy/ornamental frame.
    x.strokeStyle="#173f35";x.lineWidth=3;x.strokeRect(48,48,W-96,H-96);
    x.strokeStyle="#b99a55";x.lineWidth=1.5;x.strokeRect(61,61,W-122,H-122);
    x.strokeStyle="#173f35";x.lineWidth=1;x.strokeRect(73,73,W-146,H-146);
    function deco(cx,cy,rot){x.save();x.translate(cx,cy);x.rotate(rot);x.strokeStyle="#b99a55";x.lineWidth=2;x.beginPath();x.moveTo(-48,0);x.lineTo(-18,0);x.lineTo(0,-18);x.lineTo(18,0);x.lineTo(48,0);x.stroke();x.beginPath();x.moveTo(-32,11);x.lineTo(-11,11);x.lineTo(0,0);x.lineTo(11,11);x.lineTo(32,11);x.stroke();x.restore()}
    deco(110,110,0);deco(W-110,110,Math.PI/2);deco(W-110,H-110,Math.PI);deco(110,H-110,-Math.PI/2);
    x.textAlign="center";x.fillStyle="#173f35";x.font="bold 22px Georgia";x.fillText("CA SMART STAYCATION",W/2,135);x.fillStyle="#a27b35";x.font="12px Arial";x.fillText("PRIVATE GUEST COLLECTION",W/2,160);
    x.fillStyle="#173f35";x.font="bold 60px Georgia";x.fillText(v.certificateTitle||"SPECIAL GUEST VOUCHER",W/2,255);x.fillStyle="#a27b35";x.font="bold 76px Georgia";x.fillText(`${v.discountPercent}% OFF`,W/2,350);x.fillStyle="#62655f";x.font="22px Georgia";x.fillText("Presented with our compliments to",W/2,410);x.fillStyle="#173f35";x.font="bold 44px Georgia";x.fillText(guest||"Special Guest",W/2,468);
    x.fillStyle="#173f35";x.fillRect(300,520,1200,72);x.fillStyle="#fffaf0";x.font="bold 17px Arial";x.fillText(`VOUCHER CODE  •  ${v.code}`,W/2,550);x.font="15px Arial";x.fillText(v.expiresAt?`Valid until ${new Date(v.expiresAt).toLocaleDateString("en-PH",{year:"numeric",month:"long",day:"numeric"})}`:"No expiration date",W/2,574);
    x.fillStyle="#a27b35";x.font="bold 16px Arial";x.fillText(v.discountPercent===100?"COMPLIMENTARY STAY  •  NON-REFUNDABLE  •  NON-CANCELLABLE":"SPECIAL GUEST PRIVILEGE",W/2,645);x.strokeStyle="#b99a55";x.lineWidth=1;x.beginPath();x.moveTo(230,690);x.lineTo(1570,690);x.stroke();
    x.textAlign="left";x.fillStyle="#173f35";x.font="bold 16px Arial";x.fillText("RESERVE YOUR STAY",190,760);x.fillStyle="#a27b35";x.font="bold 17px Arial";x.fillText("casmartstaycation.github.io/cassbooking/",190,792);x.fillStyle="#62655f";x.font="14px Arial";x.fillText("Scan the QR code to book your stay.",190,820);x.fillStyle="#a27b35";x.font="italic 16px Georgia";x.fillText("A refined stay, thoughtfully prepared.",190,875);
    x.fillStyle="#fffdf7";x.fillRect(1360,735,245,195);x.strokeStyle="#b99a55";x.lineWidth=2;x.strokeRect(1360,735,245,195);x.drawImage(qr,1377,752,161,161);x.fillStyle="#173f35";x.textAlign="center";x.font="bold 12px Arial";x.fillText("SCAN TO BOOK",1482,914);return c.toDataURL("image/png")}
  async function generateCertificate(button){const id=button.dataset.voucherId;if(!id)return;try{const r=await fetch(`${API}/vouchers`,{headers:headers(),cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.message||"Unable to load voucher.");const v=(j.data||[]).find(x=>String(x._id)===String(id));if(!v)throw new Error("Voucher not found.");const guest=prompt("Enter the special guest name for this voucher:",v.specialGuestName||"");if(guest===null)return;const update=await fetch(`${API}/vouchers/${id}`,{method:"PUT",headers:headers(),body:JSON.stringify({specialGuestName:guest})});if(!update.ok)throw new Error("Unable to save special guest name.");const a=document.createElement("a");a.href=await drawLuxuryCertificate({...v,specialGuestName:guest},guest);a.download=`${v.code}-luxury-voucher.png`;a.click()}catch(e){alert(e.message||"Unable to generate certificate.")}}
  function replaceCertificateButtons(){const list=document.getElementById("voucherAdminList");if(!list)return;list.querySelectorAll("button").forEach(old=>{if(!/generate certificate/i.test(old.textContent||""))return;if(old.dataset.luxuryCertificate==="true")return;const button=old.cloneNode(true);button.dataset.luxuryCertificate="true";const id=old.dataset.voucherId||old.closest(".voucher-admin-item")?.dataset.voucherId;if(id)button.dataset.voucherId=id;button.addEventListener("click",()=>generateCertificate(button));old.replaceWith(button)})}
  function patchLoader(){if(typeof window.loadAdminVouchers!=="function"||window.loadAdminVouchers.__patched)return;const original=window.loadAdminVouchers;async function wrapped(){const result=await original();setTimeout(addDeleteButtons,0);setTimeout(replaceCertificateButtons,20);return result}wrapped.__patched=true;window.loadAdminVouchers=wrapped}
  function init(){addStyles();addTab();patchLoader();hideTab();setTimeout(()=>{addTab();patchLoader();hideTab();replaceCertificateButtons()},500);setTimeout(()=>{addTab();patchLoader();hideTab();replaceCertificateButtons()},1500)}
  document.addEventListener("DOMContentLoaded",init);const observer=new MutationObserver(()=>{addStyles();addTab();patchLoader();const card=getCard(),tab=document.getElementById("voucherManagementTab");if(card&&tab&&!tab.classList.contains("active"))hideTab();addDeleteButtons();replaceCertificateButtons()});observer.observe(document.documentElement,{childList:true,subtree:true});
})();